### ISSUE TITLE
Incomplete OSGi metadata

### ISSUE THREAD

**Issue by Mailaender** [cdk/cdk#1006]
https://github.com/cdk/cdk/pull/934 is somehow incomplete, although I don't know why:

![image](https://github.com/cdk/cdk/assets/756669/f1a831c5-8b1a-4498-82bc-5a6cebb16142)

Some imports have access restrictions for no good reason.

**Comment by johnmay** [comment]
Sorry I have no idea about OSGI, w.r.t to Java modules we do have packages that appear in multiple modules. Is that also an issue with OSGI?

**Comment by egonw** [comment]
> Is that also an issue with OSGI?

I think so. We started cleaning this up at some point, but the problem is that moving classes from one package to another is a breaking change, so we have to be careful.

Can you provide a bit more info? Maybe we can find a simple, quick solution. E.g. what CDK modules are you using? what other class are you using that conflicts with importing `org.openscience.cdk.Atom`?

**Comment by Mailaender** [comment]
I have been experimenting at https://github.com/Mailaender/openchrom/tree/cdk-maven I looked through the https://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html but I can't find anything wrong with the syntax used.

**Comment by Mailaender** [comment]
> we do have packages that appear in multiple modules

are those internal API?

**Comment by Mailaender** [comment]
I made some tests. Using the `cdk-bundle` conflicts. Using individual packages does not conflict until you add https://mvnrepository.com/artifact/org.openscience.cdk/cdk-interfaces

**Comment by egonw** [comment]
Indeed, the `cdk-interfaces` is the one the module you always needs. So, it's more like other modules conflict with this one.

**Comment by Mailaender** [comment]
* [net.openchrom.xxd.identifier.supplier.cdk](https://github.com/OpenChrom/openchrom/tree/develop/openchrom/plugins/net.openchrom.xxd.identifier.supplier.cdk)
* [net.openchrom.xxd.identifier.supplier.cdk.ui](https://github.com/OpenChrom/openchrom/tree/develop/openchrom/plugins/net.openchrom.xxd.identifier.supplier.cdk.ui)

are relevant.

**Comment by egonw** [comment]
Okay, a first step: https://github.com/OpenChrom/openchrom/pull/417

**Comment by Mailaender** [comment]
The complete error messages:

```
Access restriction: The type 'SmilesParser' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-smiles/2.9/cdk-smiles-2.9.jar')
Access restriction: The type 'SmilesParser' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-smiles/2.9/cdk-smiles-2.9.jar')
Access restriction: The type 'SmilesParser' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-smiles/2.9/cdk-smiles-2.9.jar')
Access restriction: The type 'SmilesParser' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-smiles/2.9/cdk-smiles-2.9.jar')
Access restriction: The type 'SmilesParser' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-smiles/2.9/cdk-smiles-2.9.jar')
Access restriction: The type 'SmilesParser' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-smiles/2.9/cdk-smiles-2.9.jar')
Access restriction: The type 'MolecularFormulaRange' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The type 'MolecularFormulaRange' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The type 'MolecularFormulaRange' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The type 'MolecularFormulaRange' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The type 'MolecularFormulaRange' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The type 'MolecularFormulaRange' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The type 'MolecularFormulaManipulator' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The type 'MolecularFormulaManipulator' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The type 'MolecularFormulaManipulator' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The type 'MolecularFormulaManipulator' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The type 'MolecularFormulaManipulator' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The type 'MolecularFormulaGenerator' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The type 'MolecularFormulaGenerator' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The type 'MolecularFormulaGenerator' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The type 'MDLV2000Reader' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-ctab/2.9/cdk-ctab-2.9.jar')
Access restriction: The type 'MDLV2000Reader' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-ctab/2.9/cdk-ctab-2.9.jar')
Access restriction: The type 'MDLV2000Reader' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-ctab/2.9/cdk-ctab-2.9.jar')
Access restriction: The type 'IRenderer<T>' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-render/2.9/cdk-render-2.9.jar')
Access restriction: The type 'IGenerator<T>' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-render/2.9/cdk-render-2.9.jar')
Access restriction: The type 'AtomContainerManipulator' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-standard/2.9/cdk-standard-2.9.jar')
Access restriction: The type 'AtomContainerManipulator' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-standard/2.9/cdk-standard-2.9.jar')
Access restriction: The type 'AtomContainerManipulator' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-standard/2.9/cdk-standard-2.9.jar')
Access restriction: The type 'AtomContainerManipulator' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-standard/2.9/cdk-standard-2.9.jar')
Access restriction: The type 'AtomContainerManipulator' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-standard/2.9/cdk-standard-2.9.jar')
Access restriction: The method 'SmilesParser.setStrict(boolean)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-smiles/2.9/cdk-smiles-2.9.jar')
Access restriction: The method 'SmilesParser.setStrict(boolean)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-smiles/2.9/cdk-smiles-2.9.jar')
Access restriction: The method 'SmilesParser.parseSmiles(String)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-smiles/2.9/cdk-smiles-2.9.jar')
Access restriction: The method 'SmilesParser.parseSmiles(String)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-smiles/2.9/cdk-smiles-2.9.jar')
Access restriction: The method 'MolecularFormulaRange.addIsotope(IIsotope, int, int)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The method 'MolecularFormulaManipulator.getString(IMolecularFormula)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The method 'MolecularFormulaManipulator.getMolecularFormula(String, IMolecularFormula)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The method 'MolecularFormulaManipulator.getMolecularFormula(IAtomContainer)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The method 'MolecularFormulaManipulator.getAtomContainer(IMolecularFormula)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The method 'MolecularFormulaGenerator.getAllFormulas()' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The method 'MDLV2000Reader.read(IChemFile)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-ctab/2.9/cdk-ctab-2.9.jar')
Access restriction: The method 'IRenderer<IAtomContainer>.setup(IAtomContainer, Rectangle)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-render/2.9/cdk-render-2.9.jar')
Access restriction: The method 'IRenderer<IAtomContainer>.paint(IAtomContainer, IDrawVisitor)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-render/2.9/cdk-render-2.9.jar')
Access restriction: The method 'AtomContainerManipulator.getMass(IAtomContainer)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-standard/2.9/cdk-standard-2.9.jar')
Access restriction: The method 'AtomContainerManipulator.getMass(IAtomContainer)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-standard/2.9/cdk-standard-2.9.jar')
Access restriction: The method 'AtomContainerManipulator.convertImplicitToExplicitHydrogens(IAtomContainer)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-standard/2.9/cdk-standard-2.9.jar')
Access restriction: The constructor 'SmilesParser(IChemObjectBuilder)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-smiles/2.9/cdk-smiles-2.9.jar')
Access restriction: The constructor 'SmilesParser(IChemObjectBuilder)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-smiles/2.9/cdk-smiles-2.9.jar')
Access restriction: The constructor 'MolecularFormulaRange()' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The constructor 'MolecularFormulaGenerator(IChemObjectBuilder, double, double, MolecularFormulaRange)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-formula/2.9/cdk-formula-2.9.jar')
Access restriction: The constructor 'MDLV2000Reader(InputStream)' is not API (restriction on required library '~/.m2/repository/org/openscience/cdk/cdk-ctab/2.9/cdk-ctab-2.9.jar')
```

Those packages are exported in the MANIFEST.MF, so I don't understand why this is still broken.

**Comment by egonw** [comment]
Okay, for a second I thought this made sense to me, but some 5 mins later I am no longer sure how to interpret this :/

**Comment by Mailaender** [comment]
https://github.com/mailaender/openchrom/tree/cdk-maven is my testing ground.

**Comment by johnmay** [comment]
I think the LoggingFactory is loaded dynamical (optional).

**Comment by Mailaender** [comment]
It causes this though:

```
java.lang.NoClassDefFoundError: org/openscience/cdk/tools/LoggingToolFactory
	at org.openscience.cdk.DynamicFactory.<clinit>(DynamicFactory.java:133)
	at net.openchrom.xxd.identifier.supplier.cdk.support.MoleculeMassCalculator.calculateMolecularWeight(MoleculeMassCalculator.java:111)
	at net.openchrom.xxd.identifier.supplier.cdk.support.MoleculeMassCalculator_1_Test.test10(MoleculeMassCalculator_1_Test.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:80)
	at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.start(CoreTestApplication.java:28)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
Caused by: java.lang.ClassNotFoundException: org.openscience.cdk.tools.LoggingToolFactory cannot be found by wrapped.org.openscience.cdk.cdk-core_2.10.0.SNAPSHOT
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:510)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 36 more
```

**Comment by johnmay** [comment]
Does the module depend on cdk-interfaces (where the class resides?)

**Comment by Mailaender** [comment]
I simply added all available packages referenced by `cdk-bundle`, so I don't accidentally miss anything.

**Comment by johnmay** [comment]
Maybe try adding cdk-log4 as well. This should be optional but may the OSGI is messing that up.

**Comment by Mailaender** [comment]
It seems your namespaces are colliding:

```
org.osgi.framework.BundleException: Could not resolve module: net.openchrom.xxd.identifier.supplier.cdk.ui [94]
  Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource net.openchrom.xxd.identifier.supplier.cdk.ui [osgi.identity; osgi.identity="net.openchrom.xxd.identifier.supplier.cdk.ui"; type="osgi.bundle"; version:Version="1.5.0.qualifier"; singleton:="true"] because it is exposed to package 'org.openscience.cdk' from resources org.openscience.cdk.interfaces [osgi.identity; osgi.identity="org.openscience.cdk.interfaces"; type="osgi.bundle"; version:Version="2.10.0.SNAPSHOT"] and org.openscience.cdk.core [osgi.identity; osgi.identity="org.openscience.cdk.core"; type="osgi.bundle"; version:Version="2.10.0.SNAPSHOT"] via two dependency chains.

Chain 1:
  net.openchrom.xxd.identifier.supplier.cdk.ui [osgi.identity; osgi.identity="net.openchrom.xxd.identifier.supplier.cdk.ui"; type="osgi.bundle"; version:Version="1.5.0.qualifier"; singleton:="true"]
    require: (osgi.wiring.bundle=org.openscience.cdk.interfaces)
     |
    provide: osgi.wiring.bundle: org.openscience.cdk.interfaces
  org.openscience.cdk.interfaces [osgi.identity; osgi.identity="org.openscience.cdk.interfaces"; type="osgi.bundle"; version:Version="2.10.0.SNAPSHOT"]

Chain 2:
  net.openchrom.xxd.identifier.supplier.cdk.ui [osgi.identity; osgi.identity="net.openchrom.xxd.identifier.supplier.cdk.ui"; type="osgi.bundle"; version:Version="1.5.0.qualifier"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.openscience.cdk.standard)(bundle-version>=2.10.0))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="2.10.0.SNAPSHOT"; osgi.wiring.bundle="org.openscience.cdk.standard"
  org.openscience.cdk.standard [osgi.identity; osgi.identity="org.openscience.cdk.standard"; type="osgi.bundle"; version:Version="2.10.0.SNAPSHOT"]
    import: (&(osgi.wiring.package=org.openscience.cdk)(&(version>=2.10.0)(!(version>=3.0.0))))
     |
    export: osgi.wiring.package: org.openscience.cdk
  org.openscience.cdk.core [osgi.identity; osgi.identity="org.openscience.cdk.core"; type="osgi.bundle"; version:Version="2.10.0.SNAPSHOT"]
	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

**Comment by Mailaender** [comment]
I filed https://github.com/cdk/cdk/pull/1043 now which fixes the imports at compile time. CDK is still unuseable because of the `NoClassDefFoundError: org/openscience/cdk/tools/LoggingToolFactory` but I think that is another bug. Your reflection magic seems to fail.
