### ISSUE TITLE
NoClassDefFoundError: org/openscience/cdk/tools/LoggingToolFactory in OSGi environment

### ISSUE THREAD

**Issue by Mailaender** [cdk/cdk#1044]
Split from: https://github.com/cdk/cdk/issues/1006

```
java.lang.NoClassDefFoundError: org/openscience/cdk/tools/LoggingToolFactory
	at org.openscience.cdk.DynamicFactory.<clinit>(DynamicFactory.java:133)
	at org.openscience.cdk.silent.SilentChemObjectBuilder$Holder.<init>(SilentChemObjectBuilder.java:121)
	at org.openscience.cdk.silent.SilentChemObjectBuilder$Holder.<clinit>(SilentChemObjectBuilder.java:119)
	at org.openscience.cdk.silent.SilentChemObjectBuilder.getInstance(SilentChemObjectBuilder.java:265)
```

I don't understand why this happens as `cdk-core` has a proper dependency on `cdk-interfaces`:

```
Manifest-Version: 1.0
Created-By: Apache Maven Bundle Plugin 5.1.8
Build-Jdk-Spec: 17
Specification-Title: cdk-core
Specification-Version: 2.10
Implementation-Title: cdk-core
Implementation-Version: 2.10-SNAPSHOT
Bnd-LastModified: 1708616291669
Bundle-Description: Modular library for Cheminformatics
Bundle-License: http://www.gnu.org/licenses/lgpl.html
Bundle-ManifestVersion: 2
Bundle-Name: cdk-core
Bundle-SymbolicName: org.openscience.cdk.core
Bundle-Version: 2.10.0.SNAPSHOT
DynamicImport-Package: org.slf4j,org.apache.logging.log4j
Export-Package: org.openscience.cdk;version="2.10.0.SNAPSHOT";uses:="jav
 ax.vecmath,org.openscience.cdk.interfaces",org.openscience.cdk.atomtype
 ;version="2.10.0.SNAPSHOT";uses:="org.openscience.cdk.exception,org.ope
 nscience.cdk.interfaces",org.openscience.cdk.config;version="2.10.0.SNA
 PSHOT";uses:="org.openscience.cdk.exception,org.openscience.cdk.interfa
 ces,org.openscience.cdk.tools",org.openscience.cdk.config.atomtypes;ver
 sion="2.10.0.SNAPSHOT";uses:="org.openscience.cdk.interfaces,org.xml.sa
 x,org.xml.sax.helpers",org.openscience.cdk.config.data;version="2.10.0.
 SNAPSHOT",org.openscience.cdk.fingerprint;version="2.10.0.SNAPSHOT";use
 s:="org.openscience.cdk.exception,org.openscience.cdk.interfaces",org.o
 penscience.cdk.graph;version="2.10.0.SNAPSHOT";uses:="org.openscience.c
 dk.exception,org.openscience.cdk.interfaces",org.openscience.cdk.graph.
 matrix;version="2.10.0.SNAPSHOT";uses:="org.openscience.cdk.interfaces"
 ,org.openscience.cdk.io;version="2.10.0.SNAPSHOT";uses:="org.openscienc
 e.cdk.exception,org.openscience.cdk.io.listener,org.openscience.cdk.io.
 setting",org.openscience.cdk.io.iterator;version="2.10.0.SNAPSHOT";uses
 :="org.openscience.cdk.exception,org.openscience.cdk.interfaces,org.ope
 nscience.cdk.io",org.openscience.cdk.io.random;version="2.10.0.SNAPSHOT
 ";uses:="org.openscience.cdk.exception,org.openscience.cdk.interfaces,o
 rg.openscience.cdk.io,org.openscience.cdk.io.listener,org.openscience.c
 dk.io.setting,org.openscience.cdk.tools",org.openscience.cdk.io.setting
 ;version="2.10.0.SNAPSHOT";uses:="org.openscience.cdk.exception,org.ope
 nscience.cdk.interfaces",org.openscience.cdk.ringsearch;version="2.10.0
 .SNAPSHOT";uses:="org.openscience.cdk.interfaces",org.openscience.cdk.s
 group;version="2.10.0.SNAPSHOT";uses:="javax.vecmath,org.openscience.cd
 k.interfaces",org.openscience.cdk.stereo;version="2.10.0.SNAPSHOT";uses
 :="org.openscience.cdk.interfaces",org.openscience.cdk.tools.manipulato
 r;version="2.10.0.SNAPSHOT";uses:="org.openscience.cdk.interfaces,org.o
 penscience.cdk.sgroup",org.openscience.cdk.tools.periodictable;version=
 "2.10.0.SNAPSHOT"
Import-Package: javax.vecmath;resolution:=optional,javax.xml.parsers;res
 olution:=optional,org.openscience.cdk.exception;resolution:=optional;ve
 rsion="[2.10,3)",org.openscience.cdk.interfaces;resolution:=optional;ve
 rsion="[2.10,3)",org.openscience.cdk.io.listener;resolution:=optional;v
 ersion="[2.10,3)",org.openscience.cdk.isomorphism.matchers;resolution:=
 optional;version="[2.10,3)",org.openscience.cdk.tools;resolution:=optio
 nal;version="[2.10,3)",org.xml.sax;resolution:=optional,org.xml.sax.hel
 pers;resolution:=optional
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Tool: Bnd-6.3.1.202206071316
```

**Comment by johnmay** [comment]
Can you give a description of how to reproduce presuming I have no knowledge of OSGi (of which I am becoming more grateful :)).

I suspect it could be a class within the logger is not found and that error is getting lost.

As Egon says we have split packages because much of this written before such issues existed. This is a know blocker for using Jigsaw modules with CDK. Changing/enforcing that would be a major undertaking and currently not worth it IMO.

**Comment by egonw** [comment]
> we have split packages because much of this written before such issues existed. This is a know blocker for using Jigsaw modules with CDK.

I hope that this is something we can address in the grant we have to work on the CDK

**Comment by johnmay** [comment]
> > we have split packages because much of this written before such issues existed. This is a know blocker for using Jigsaw modules with CDK.
> 
> I hope that this is something we can address in the grant we have to work on the CDK

Yeah it’s not hard, but you break everyone else’s code for minimal benefit. Almost change for changes sake

**Comment by Mailaender** [comment]
I created https://github.com/Mailaender/cdk-osgi-minimal

**Comment by johnmay** [comment]
Thanks,

Why doesn't

```
org.openscience.cdk;version="2.10.0.SNAPSHOT";uses:="jav
 ax.vecmath,org.openscience.cdk.interfaces",org.openscience.cdk.atomtype
 ;version="2.10.0.SNAPSHOT";
```

Need to be:

```
org.openscience.cdk;version="2.10.0.SNAPSHOT";uses:="jav
 ax.vecmath,org.openscience.cdk.interfaces,org.openscience.cdk.tools"
```

Context the DynamicFactory is in ```org.openscience.cdk``` and the logging tool is in ```org.openscience.cdk.tools```

**Comment by Mailaender** [comment]
> we should check which (if more than one) maven bundles have classes from the Java package `org.openscience.cdk.tools`.

There are multiple ones. You systematically define packages inside unrelated plugins.

**Comment by johnmay** [comment]
Remember there was not "plugins" 20 years ago :-)

**Comment by johnmay** [comment]
@Mailaender Need more details on https://github.com/Mailaender/cdk-osgi-minimal. I've installed eclipse, seems like it's maybe "Help > Install New Software". Then what? Trying to find info on this it is all just about "installing Git" and not "plugins from git"

**Comment by Mailaender** [comment]
Git is shipped with Eclipse. Press `File` → `Import` → `Git` → `Projects from Git`.

**Comment by Mailaender** [comment]
I get

> Access restriction: The constructor 'LoggingToolFactory()' is not API (restriction on required library '/home/matthias/.m2/repository/org/openscience/cdk/cdk-interfaces/2.10-SNAPSHOT/cdk-interfaces-2.10-SNAPSHOT.jar')

so the logging tool is not in `org.openscience.cdk.tools`.

**Comment by Mailaender** [comment]
> the logging tool is in `org.openscience.cdk.tools`

There is no `cdk-tools` package.

**Comment by johnmay** [comment]
> > the logging tool is in `org.openscience.cdk.tools`
> 
> There is no `cdk-tools` package.

???

Correct there is no ``cdk-tools`` module. But there is a ```org.openscience.cdk.tools``` package which is part of ``cdk-interfaces``. These look like package rather than module annotations.

**Comment by johnmay** [comment]
The access restrictions is an eclipse thing. I think you essentially need to treat all the CDK as public API, not ideal but you're trying to constrain/impose rules and restrictions on something which just wasn't designed that way.

**Comment by Mailaender** [comment]
I tried prefixing your packages to avoid conflicts, but that then requires making many functions public so it feels wrong.

**Comment by johnmay** [comment]
I think it just can't be done in the current version of OSGI. Square peg, round hole.

https://nirmalsasidharan.wordpress.com/2010/09/02/split-packages-an-osgi-nightmare/

For now I think the most sensible thing might just to make a single monolithic CDK Jar (i.e. cdk-bundle.jar) and expose it that way. Most of the size of that is 3rd party libraries.

We have it as a possible item for future to avoid split packages (see #823) but this is a big ask and honestly I'm not convinced of OSGI/Jigsaw benefits hence it's not an urgent priority. Note the modules are primarily dependency orientated to work nicely with maven, hence stuff like fingerprint functionality package is split based on which dependencies/3rd party parts are needed. Without that you end up with large bloat in each module and it's not better than just having a single uber JAR. Trying to get things into maven was pain enough due to cyclic dependencies between main/test JARs (when things were built with ANT).

**Comment by Mailaender** [comment]
I think you are right. As a test, I renamed 

```patch
+import org.openscience.cdk.interfaces.tools.ILoggingTool;
+import org.openscience.cdk.interfaces.tools.LoggingToolFactory;
-import org.openscience.cdk.tools.ILoggingTool;
-import org.openscience.cdk.tools.LoggingToolFactory;
```

but it will only crash on another occasion:

> java.lang.NoClassDefFoundError: org/openscience/cdk/exception/NoSuchAtomException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2555)
	at org.openscience.cdk.DynamicFactory.register(DynamicFactory.java:320)
	at org.openscience.cdk.DynamicFactory.register(DynamicFactory.java:283)
	at org.openscience.cdk.silent.SilentChemObjectBuilder$Holder.<init>(SilentChemObjectBuilder.java:147)
	at org.openscience.cdk.silent.SilentChemObjectBuilder$Holder.<clinit>(SilentChemObjectBuilder.java:119)
	at org.openscience.cdk.silent.SilentChemObjectBuilder.getInstance(SilentChemObjectBuilder.java:265)
	at net.openchrom.xxd.identifier.supplier.cdk.converter.CDKSmilesToMoleculeConverter.<init>(CDKSmilesToMoleculeConverter.java:33)
	at net.openchrom.xxd.identifier.supplier.cdk.converter.OPSINIupacToMoleculeConverter.<init>(OPSINIupacToMoleculeConverter.java:25)
	at net.openchrom.xxd.identifier.supplier.cdk.converter.OPSINIupacToMoleculeConverter_Test.setUp(OPSINIupacToMoleculeConverter_Test.java:28)
	at junit.framework.TestCase.runBare(TestCase.java:140)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:80)
	at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.start(CoreTestApplication.java:28)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
Caused by: java.lang.ClassNotFoundException: org.openscience.cdk.exception.NoSuchAtomException cannot be found by org.openscience.cdk.silent_2.10.0.SNAPSHOT
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:487)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 39 more

A monolithic CDK.jar supplied via Maven would indeed solve the problem. Our redistribution at https://github.com/OpenChrom/openchrom3rdpl/tree/develop/openchrom/plugins/net.openchrom.thirdpartylibraries.cdk/libraries does the same thing.

**Comment by johnmay** [comment]
>A monolithic CDK.jar supplied via Maven would indeed solve the problem. Our redistribution at

I think perhaps can do slightly better by removing the dependencies and doing those via OSGI still - if that makes sense?

**Comment by Mailaender** [comment]
Indeed, I unbundled those https://github.com/OpenChrom/openchrom3rdpl/commit/d8612618c636850f950c2a0b742a5c7d2e9b5d67 as well. I think we only really need `javax.vecmath`.

**Comment by johnmay** [comment]
OK to close, we will make an effort to undo/avoid split packages in the next major version. I am actually more leaning towards fewer modules, but that's for another discussion.

**Comment by Mailaender** [comment]
Did you address the OSGi compatibility in the 2.10 release already?

**Comment by johnmay** [comment]
As per my comment there is nothing we can do without breaking the API which will be a 3.0 which might not be till 2030 (who knows). I'm not an OSGi user so unless you provide a patch to fix it that doesn't break existing APIs we can't do much.

**Comment by Mailaender** [comment]
There is also a new problem since CDK 2.10 where a dependency has split API and implementation in several packages which also fails in an OSGi environment at runtime:
```
Caused by: java.lang.NoClassDefFoundError: io/github/dan2097/jnainchi/InchiOptions$InchiOptionsBuilder
	at org.openscience.cdk.inchi.InChIGenerator.<clinit>(InChIGenerator.java:101)
	at org.openscience.cdk.inchi.InChIGeneratorFactory.getInChIGenerator(InChIGeneratorFactory.java:141)
```

**Comment by johnmay** [comment]
Perhaps OSGi can't be used with CDK? Seems much more effort than it's worth, just put everything in a single uber JAR and be done.

Not much we can do about a dependency unfortunately particularly a critical one like JNA InChI.

**Comment by Mailaender** [comment]
Why do you need platform dependent code for something like InChi?

**Comment by johnmay** [comment]
Not sure what you mean? Do you mean why do we need to use native shared libraries? 

The reason is the InChI code is so complex (not in a good way) that it would be almost impossible to replicate/rewrite. Unlike SMILES which is simple and therefore has many different (and sometimes incompatible implementations there is only **ONE** InChI.

**Comment by Mailaender** [comment]
Shared platform dependent libraries consumed from a repository governed by a private person that need to be unpacked, code signed, repackaged for a task that does not require interfacing with hardware nor needs to be speed optimized is a bit of a hazzle for distributors, so I am asking for the gain. It seems this was not required pre 2.10 and forces me to rethink how I handle this dependency.

**Comment by johnmay** [comment]
Can you explain a bit more what your issue is as I'm very lost?

If you issue is with JNA InChI that was added a dependency in CDK 2.7.1 (https://github.com/cdk/cdk/releases/tag/cdk-2.7.1). We used to JNI InChI but that was outdated, if effectively worked the same but used Java's JNI rather Java's JNA to interface with native code.

**Comment by Mailaender** [comment]
Yeah, sorry, that was my bad. https://mvnrepository.com/artifact/org.openscience.cdk/cdk-inchi/2.9 also has the JNA InChi which does not work with @eclipse-m2e by default. The breakage was introduced in https://github.com/openchrom/openchrom3rdpl/commit/4671bfc36055d662516920b9c3946ae908234c89 where I manually trimmed the CDK.jar to only contain the `org.openscience.cdk` namespace. I didn't understand that InChi generation was relying on native code. It won't break on compile time, only on runtime, which makes this even nastier. I will join the CDK user meeting this year. Maybe I can help work something out that works better in an OSGi context, even though it may not be fully featured.
