### ISSUE TITLE
cdk-2.9 Provider for javax.xml.parsers.SAXParserFactory cannot be found

### ISSUE THREAD

**Issue by J-Siu** [cdk/cdk#1045]
Groovy test script (cdk.groovy):
```
import org.openscience.cdk.fingerprint.*;
import org.openscience.cdk.smiles.*;
import org.openscience.cdk.silent.*;
import org.openscience.cdk.similarity.*;

smilesParser = new SmilesParser(SilentChemObjectBuilder.getInstance())

smiles1 = 'ClC1=CC=CC(Cl)=C1C2=NOC(C3CC3)=C2COC4=CC(Cl)=C(C(C5)(O)CN5C6=CC(C(O)=O)=CC=N6)C=C4'

mol1 = smilesParser.parseSmiles(smiles1)
fingerprinter = new ExtendedFingerprinter()
bitset1 = fingerprinter.getFingerprint(mol1)
```

Command:

No error if we use 2.8
```
groovy -cp cdk-2.8.jar cdk.groovy                                                      
```

Error if we use 2.9
```
groovy -cp cdk-2.9.jar cdk.groovy                                                      
```
Error:
```
Caught: javax.xml.parsers.FactoryConfigurationError: Provider for javax.xml.parsers.SAXParserFactory cannot be found
javax.xml.parsers.FactoryConfigurationError: Provider for javax.xml.parsers.SAXParserFactory cannot be found
	at org.openscience.cdk.config.atomtypes.OWLAtomTypeReader.init(OWLAtomTypeReader.java:69)
	at org.openscience.cdk.config.atomtypes.OWLAtomTypeReader.<init>(OWLAtomTypeReader.java:60)
	at org.openscience.cdk.config.OWLBasedAtomTypeConfigurator.readAtomTypes(OWLBasedAtomTypeConfigurator.java:62)
	at org.openscience.cdk.config.AtomTypeFactory.readConfiguration(AtomTypeFactory.java:236)
	at org.openscience.cdk.config.AtomTypeFactory.readConfiguration(AtomTypeFactory.java:209)
	at org.openscience.cdk.config.AtomTypeFactory.<init>(AtomTypeFactory.java:107)
	at org.openscience.cdk.config.AtomTypeFactory.getInstance(AtomTypeFactory.java:165)
	at org.openscience.cdk.atomtype.CDKAtomTypeMatcher.<init>(CDKAtomTypeMatcher.java:71)
	at org.openscience.cdk.atomtype.CDKAtomTypeMatcher.getInstance(CDKAtomTypeMatcher.java:84)
	at org.openscience.cdk.atomtype.CDKAtomTypeMatcher.getInstance(CDKAtomTypeMatcher.java:76)
	at org.openscience.cdk.tools.manipulator.AtomContainerManipulator.percieveAtomTypesAndConfigureAtoms(AtomContainerManipulator.java:1613)
	at org.openscience.cdk.fingerprint.Fingerprinter.getBitFingerprint(Fingerprinter.java:168)
	at org.openscience.cdk.fingerprint.Fingerprinter.getBitFingerprint(Fingerprinter.java:186)
	at org.openscience.cdk.fingerprint.ExtendedFingerprinter.getBitFingerprint(ExtendedFingerprinter.java:161)
	at org.openscience.cdk.fingerprint.ExtendedFingerprinter.getBitFingerprint(ExtendedFingerprinter.java:101)
	at org.openscience.cdk.fingerprint.ExtendedFingerprinter.getFingerprint(ExtendedFingerprinter.java:218)
	at cdk.run(cdk.groovy:67)
```

**Comment by johnmay** [comment]
Which JVM version is Groovy using?

**Comment by J-Siu** [comment]
@johnmay 

The above command line test was done on MacOS. Groovy, Java are installed from brew.

```
$ java -version
openjdk version "21.0.2" 2024-01-16
OpenJDK Runtime Environment Homebrew (build 21.0.2)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.2, mixed mode, sharing)

$ groovy -version
Groovy Version: 4.0.18 JVM: 21.0.2 Vendor: Homebrew OS: Mac OS X
```

The script is also tested in both Win11 and MacOS Eclipse. Groovy project are using:
- Groovy Development Tools 5.2.0.RELEASE
- JavaSE-20

They give same result as command line. No issue with cdk-2.8, but 2.9 gives error.

**Comment by J-Siu** [comment]
Not sure if it is related, I also noticed that 2.9, when compare with 2.8, a lot of the javax directories are removed.

Line count for all `javax` directories in cdk jar:
```
$ jar tvf cdk-2.8.jar|grep javax|wc -l
     252
$ jar tvf cdk-2.9.jar|grep javax|wc -l
      94
```

Narrow down to `javax.xml.parsers`:
```
$ jar tvf cdk-2.8.jar|grep javax.xml.parsers|wc -l
      18
js@mba2 2024-02-28 4:14:46.944 ~/code/jar
$ jar tvf cdk-2.9.jar|grep javax.xml.parsers|wc -l
       9
```

**Comment by johnmay** [comment]
Javax is now jakarta, and looks like Java 21 removed some of the parser APIS. You can add in the missing dependency or use Java 8/11/17 (maybe). Curiously our Java 21 build on Git works OK and will test that functionality. Perhaps the Homebrew Java is missing some parts.

Following on from that do you definitely want the ExtendedFingerprinter?

**Comment by johnmay** [comment]
Can you try it directly in Java (or Jshell).

```
$ /opt/jdk-21.jdk/Contents/Home/bin/jshell --class-path ~/Downloads/cdk-2.9.jar
```

The following (Java equivalent of your groovy script) works OK

```
import org.openscience.cdk.fingerprint.*;
import org.openscience.cdk.smiles.*;
import org.openscience.cdk.silent.*;
import org.openscience.cdk.similarity.*;

var smilesParser = new SmilesParser(SilentChemObjectBuilder.getInstance());

var smiles1 = "ClC1=CC=CC(Cl)=C1C2=NOC(C3CC3)=C2COC4=CC(Cl)=C(C(C5)(O)CN5C6=CC(C(O)=O)=CC=N6)C=C4";

var mol1 = smilesParser.parseSmiles(smiles1);
var fingerprinter = new ExtendedFingerprinter();
var bitset1 = fingerprinter.getFingerprint(mol1);
```

**Comment by J-Siu** [comment]
@johnmay Interesting, as you mentioned, jshell works without issue.

I wonder if groovy issue is due cdk-2.9 has no `META-INF/services/javax.xml.*`.

```
$ jar tvf cdk-2.8.jar|grep javax|grep META             
     0 Wed Sep 14 14:57:36 EDT 2022 META-INF/maven/javax.vecmath/
     0 Wed Sep 14 14:57:36 EDT 2022 META-INF/maven/javax.vecmath/vecmath/
  5505 Wed Sep 14 14:57:36 EDT 2022 META-INF/maven/javax.vecmath/vecmath/pom.xml
   113 Wed Sep 14 14:57:36 EDT 2022 META-INF/maven/javax.vecmath/vecmath/pom.properties
    53 Wed Sep 14 14:57:38 EDT 2022 META-INF/services/javax.xml.datatype.DatatypeFactory
    51 Wed Sep 14 14:57:38 EDT 2022 META-INF/services/javax.xml.parsers.DocumentBuilderFactory
    45 Wed Sep 14 14:57:38 EDT 2022 META-INF/services/javax.xml.parsers.SAXParserFactory
    46 Wed Sep 14 14:57:38 EDT 2022 META-INF/services/javax.xml.stream.XMLEventFactory
    52 Wed Sep 14 14:57:38 EDT 2022 META-INF/services/javax.xml.validation.SchemaFactory
    51 Wed Sep 14 14:57:38 EDT 2022 META-INF/services/javax.xml.transform.TransformerFactory
    38 Wed Sep 14 14:57:38 EDT 2022 META-INF/services/javax.xml.xpath.XPathFactory
   855 Wed Sep 14 14:57:38 EDT 2022 META-INF/services/javax.annotation.processing.Processor
   135 Wed Sep 14 14:57:38 EDT 2022 META-INF/services/javax.imageio.spi.ImageWriterSpi
     0 Wed Sep 14 14:57:40 EDT 2022 META-INF/maven/javax.annotation/
     0 Wed Sep 14 14:57:40 EDT 2022 META-INF/maven/javax.annotation/javax.annotation-api/
 14478 Wed Sep 14 14:57:40 EDT 2022 META-INF/maven/javax.annotation/javax.annotation-api/pom.xml
   121 Wed Sep 14 14:57:40 EDT 2022 META-INF/maven/javax.annotation/javax.annotation-api/pom.properties

$ jar tvf cdk-2.9.jar|grep javax|grep META
     0 Tue Nov 07 08:53:32 EST 2023 META-INF/maven/javax.vecmath/
     0 Tue Nov 07 08:53:32 EST 2023 META-INF/maven/javax.vecmath/vecmath/
  5505 Tue Nov 07 08:53:32 EST 2023 META-INF/maven/javax.vecmath/vecmath/pom.xml
   113 Tue Nov 07 08:53:32 EST 2023 META-INF/maven/javax.vecmath/vecmath/pom.properties
   855 Tue Nov 07 08:53:32 EST 2023 META-INF/services/javax.annotation.processing.Processor
   135 Tue Nov 07 08:53:34 EST 2023 META-INF/services/javax.imageio.spi.ImageWriterSpi
```

**Comment by johnmay** [comment]
Try adding it and see if it fixes it? JARs are just zip files. I don’t recall changing how we packaged it.- JohnOn 28 Feb 2024, at 14:17, John Sing Dao Siu ***@***.***> wrote:﻿
@johnmay Interesting, as you mentioned, jshell works without issue.
I wonder if groovy issue is due cdk-2.9 has no META-INF/services/javax.xml.*.
$ jar tvf cdk-2.8.jar|grep javax|grep META             
     0 Wed Sep 14 14:57:36 EDT 2022 META-INF/maven/javax.vecmath/
     0 Wed Sep 14 14:57:36 EDT 2022 META-INF/maven/javax.vecmath/vecmath/
  5505 Wed Sep 14 14:57:36 EDT 2022 META-INF/maven/javax.vecmath/vecmath/pom.xml
   113 Wed Sep 14 14:57:36 EDT 2022 META-INF/maven/javax.vecmath/vecmath/pom.properties
    53 Wed Sep 14 14:57:38 EDT 2022 META-INF/services/javax.xml.datatype.DatatypeFactory
    51 Wed Sep 14 14:57:38 EDT 2022 META-INF/services/javax.xml.parsers.DocumentBuilderFactory
    45 Wed Sep 14 14:57:38 EDT 2022 META-INF/services/javax.xml.parsers.SAXParserFactory
    46 Wed Sep 14 14:57:38 EDT 2022 META-INF/services/javax.xml.stream.XMLEventFactory
    52 Wed Sep 14 14:57:38 EDT 2022 META-INF/services/javax.xml.validation.SchemaFactory
    51 Wed Sep 14 14:57:38 EDT 2022 META-INF/services/javax.xml.transform.TransformerFactory
    38 Wed Sep 14 14:57:38 EDT 2022 META-INF/services/javax.xml.xpath.XPathFactory
   855 Wed Sep 14 14:57:38 EDT 2022 META-INF/services/javax.annotation.processing.Processor
   135 Wed Sep 14 14:57:38 EDT 2022 META-INF/services/javax.imageio.spi.ImageWriterSpi
     0 Wed Sep 14 14:57:40 EDT 2022 META-INF/maven/javax.annotation/
     0 Wed Sep 14 14:57:40 EDT 2022 META-INF/maven/javax.annotation/javax.annotation-api/
 14478 Wed Sep 14 14:57:40 EDT 2022 META-INF/maven/javax.annotation/javax.annotation-api/pom.xml
   121 Wed Sep 14 14:57:40 EDT 2022 META-INF/maven/javax.annotation/javax.annotation-api/pom.properties

$ jar tvf cdk-2.9.jar|grep javax|grep META
     0 Tue Nov 07 08:53:32 EST 2023 META-INF/maven/javax.vecmath/
     0 Tue Nov 07 08:53:32 EST 2023 META-INF/maven/javax.vecmath/vecmath/
  5505 Tue Nov 07 08:53:32 EST 2023 META-INF/maven/javax.vecmath/vecmath/pom.xml
   113 Tue Nov 07 08:53:32 EST 2023 META-INF/maven/javax.vecmath/vecmath/pom.properties
   855 Tue Nov 07 08:53:32 EST 2023 META-INF/services/javax.annotation.processing.Processor
   135 Tue Nov 07 08:53:34 EST 2023 META-INF/services/javax.imageio.spi.ImageWriterSpi

**Comment by J-Siu** [comment]
I end up copying more and more files from 2.8 into 2.9.

Following are the files copied:
```
META-INF/services: javax.xml.datatype.DatatypeFactory
META-INF/services: javax.xml.parsers.DocumentBuilderFactory
META-INF/services: javax.xml.parsers.SAXParserFactory
META-INF/services: javax.xml.stream.XMLEventFactory
META-INF/services: javax.xml.transform.TransformerFactory
META-INF/services: javax.xml.validation.SchemaFactory
META-INF/services: javax.xml.xpath.XPathFactory
META-INF/services: org.w3c.dom.DOMImplementationSourceList
META-INF/services: org.xml.sax.driver
javax: annotation
javax/xml: XMLConstants.class
javax/xml: datatype
javax/xml: namespace
javax/xml/parsers: FilePathToURI.class
javax/xml/parsers: SecuritySupport$1.class
javax/xml/parsers: SecuritySupport$2.class
javax/xml/parsers: SecuritySupport$3.class
javax/xml/parsers: SecuritySupport$4.class
javax/xml/parsers: SecuritySupport$5.class
javax/xml/parsers: SecuritySupport.class
javax/xml: stream
javax/xml/transform: SecuritySupport$1.class
javax/xml/transform: SecuritySupport$2.class
javax/xml/transform: SecuritySupport$3.class
javax/xml/transform: SecuritySupport$4.class
javax/xml/transform: SecuritySupport$5.class
javax/xml/transform: SecuritySupport.class
javax/xml/transform: stax
javax/xml/transform/stream: FilePathToURI.class
javax/xml: validation
javax/xml: xpath
org/apache: xerces
org/apache: xml
```

And doing `groovy -cp ~/code/jar/cdk_2.9_added cdk.groovy` gives following error:
```
Caught: java.lang.IncompatibleClassChangeError: Class org.apache.xerces.parsers.AbstractSAXParser$AttributesProxy does not implement the requested interface org.xml.sax.Attributes
java.lang.IncompatibleClassChangeError: Class org.apache.xerces.parsers.AbstractSAXParser$AttributesProxy does not implement the requested interface org.xml.sax.Attributes
	at org.openscience.cdk.config.atomtypes.OWLAtomTypeHandler.startAtomTypeElement(OWLAtomTypeHandler.java:128)
	at org.openscience.cdk.config.atomtypes.OWLAtomTypeHandler.startElement(OWLAtomTypeHandler.java:120)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.openscience.cdk.config.atomtypes.OWLAtomTypeReader.readAtomTypes(OWLAtomTypeReader.java:115)
	at org.openscience.cdk.config.OWLBasedAtomTypeConfigurator.readAtomTypes(OWLBasedAtomTypeConfigurator.java:63)
	at org.openscience.cdk.config.AtomTypeFactory.readConfiguration(AtomTypeFactory.java:236)
	at org.openscience.cdk.config.AtomTypeFactory.readConfiguration(AtomTypeFactory.java:209)
	at org.openscience.cdk.config.AtomTypeFactory.<init>(AtomTypeFactory.java:107)
	at org.openscience.cdk.config.AtomTypeFactory.getInstance(AtomTypeFactory.java:165)
	at org.openscience.cdk.atomtype.CDKAtomTypeMatcher.<init>(CDKAtomTypeMatcher.java:71)
	at org.openscience.cdk.atomtype.CDKAtomTypeMatcher.getInstance(CDKAtomTypeMatcher.java:84)
	at org.openscience.cdk.atomtype.CDKAtomTypeMatcher.getInstance(CDKAtomTypeMatcher.java:76)
	at org.openscience.cdk.tools.manipulator.AtomContainerManipulator.percieveAtomTypesAndConfigureAtoms(AtomContainerManipulator.java:1613)
	at org.openscience.cdk.fingerprint.Fingerprinter.getBitFingerprint(Fingerprinter.java:168)
	at org.openscience.cdk.fingerprint.Fingerprinter.getBitFingerprint(Fingerprinter.java:186)
	at org.openscience.cdk.fingerprint.ExtendedFingerprinter.getBitFingerprint(ExtendedFingerprinter.java:161)
	at org.openscience.cdk.fingerprint.ExtendedFingerprinter.getBitFingerprint(ExtendedFingerprinter.java:101)
	at cdk.run(cdk.groovy:12)
```

And I can't go any further.

**Comment by johnmay** [comment]
I think if this works in Java/Jshell 21 this is a groovy config issue so not much we can do. We didn't change how things were packaged but did update some dependencies (e.g. xerces - which is alway a pain.)

**Comment by johnmay** [comment]
Closing as can't fix - likely groovy config issue

**Comment by egonw** [comment]
I'll see if we can make this part of the NWO Open Science grant. Topic-wise fits well in that.

**Comment by egonw** [comment]
> likely groovy config issue

Okay, @rvdploeg and I just had a look at it together. It does not seem to be a Groovy so much. We could confirm that the 2.8 jar contains a copy of Xerces, and 2.9 (and 2.10) do not. But, the CDK should be okay with that, so I also think it's a CDK bug that I have to fix.

Then again, just adding Xerces to the classpath is not a workaround:

```shell
groovy -cp cdk-2.9.jar:xercesImpl-2.12.2.jar cdk.groovy
```

That fails with the same stacktrace.

**Comment by johnmay** [comment]
It could be the OSGI or Jigsaw manifest stuff.. take a look at the build files (pom.xml) and try turning off all the extra meta data that goes in. Don't actually want to remove it but might help pin down the problem.

This stuff:

```xml
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.4.2</version>
                <inherited>true</inherited>
                <configuration>
                    <archive>
                        <manifest>
                            <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                            <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
                        </manifest>
                        <manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
                    </archive>
                </configuration>
```

```xml
<plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <version>5.1.9</version>
                <configuration>
                    <instructions>
                        <Import-Package>
                            *;resolution:=optional,
                            org.slf4j;resolution:=dynamic,
                            org.apache.logging.log4j;resolution:=dynamic
                        </Import-Package>
                        <Export-Package>
                            *;version="${project.version}";-noimport:=true,
                        </Export-Package>
                    </instructions>
                    <noWarningProjectTypes>pom</noWarningProjectTypes>
                </configuration>
                <executions>
                    <execution>
                        <id>bundle-manifest</id>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>manifest</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
