### ISSUE TITLE
NPE in atom typer causing failing unit tests

### ISSUE THREAD

**Issue by egonw** [cdk/cdk#282]
NPEs like:

    java.lang.NullPointerException: null
	at org.openscience.cdk.atomtype.CDKAtomTypeMatcher.isAcceptable(CDKAtomTypeMatcher.java:2516)
	at org.openscience.cdk.atomtype.CDKAtomTypeMatcher.perceiveCarbons(CDKAtomTypeMatcher.java:480)
	at org.openscience.cdk.atomtype.CDKAtomTypeMatcher.findMatchingAtomType(CDKAtomTypeMatcher.java:131)
	at org.openscience.cdk.atomtype.CDKAtomTypeMatcher.findMatchingAtomType(CDKAtomTypeMatcher.java:122)
	at org.openscience.cdk.atomtype.ReactionStructuresTest.testM10(ReactionStructuresTest.java:334)

See https://jenkins.bigcat.unimaas.nl/job/cdk/lastCompletedBuild/testReport/

**Comment by egonw** [comment]
Patch was merged in.
