### ISSUE TITLE
Molecular formula exception with bismuth subcarbonate

### ISSUE THREAD

**Issue by ficolas2** [cdk/cdk#553]
When getting the molecular formula of bismuth subcarbonate using a string and the MolecularFormulaManipulator, a exception is thrown.

The problem seems to be that in MolecularFormulaManipulator, in the breakExtractor method, when there is more text after the number that multiplies the parenthesis, the text is taken into the string to be parsed to an integer, causing the NumberFormatException.
However, I don't think this is the only problem, I think that the multipliers of the second parenthesis (if any, in the example at the bottom there aren't any, but take the invented formula "(BiO)2(CO3)2" as an example) may be ignored.
I will do more testing tomorrow, and may submit a pull request if I manage to fix it.

`MolecularFormulaManipulator.getMolecularFormula("(BiO)2(CO3)", DefaultChemObjectBuilder.getInstance());`

`Exception in thread "main" java.lang.NumberFormatException: For input string: "02CO3"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.valueOf(Unknown Source)
	at org.openscience.cdk.tools.manipulator.MolecularFormulaManipulator.breakExtractor(MolecularFormulaManipulator.java:1252)
	at org.openscience.cdk.tools.manipulator.MolecularFormulaManipulator.simplifyMolecularFormula(MolecularFormulaManipulator.java:1147)
	at org.openscience.cdk.tools.manipulator.MolecularFormulaManipulator.getMolecularFormula(MolecularFormulaManipulator.java:682)
	at org.openscience.cdk.tools.manipulator.MolecularFormulaManipulator.getMolecularFormula(MolecularFormulaManipulator.java:553)
	at org.openscience.cdk.tools.manipulator.MolecularFormulaManipulator.getMolecularFormula(MolecularFormulaManipulator.java:531)`

**Comment by johnmay** [comment]
The CDK MFs are really only meant to support sum formulae not line formulae (although not really a line formula in this case). The sum formula for bismuth subcarbonate would ``CO5Bi2``. However it is reasonable to allow the parser to parse your example correctly so feel free to submit a PR.

**Comment by ficolas2** [comment]
Created pull request.
[https://github.com/cdk/cdk/pull/554](#554)
