### ISSUE TITLE
possible outdated code in Expr?

### ISSUE THREAD

**Issue by egonw** [cdk/cdk#607]
One of the Groovy example caused an `UnsupportedOperationException`. It looks like `Expr.getTotalHCount()` is using `IAtom.bonds()` which is (not) longer supported? Does the `Expr` class need to be updated?

```
Caught: java.lang.UnsupportedOperationException
java.lang.UnsupportedOperationException
        at org.openscience.cdk.Atom.bonds(Atom.java:260)
        at org.openscience.cdk.isomorphism.matchers.Expr.getTotalHCount(Expr.java:431)
        at org.openscience.cdk.isomorphism.matchers.Expr.matches(Expr.java:278)
        at org.openscience.cdk.isomorphism.matchers.Expr.matches(Expr.java:359)
        at org.openscience.cdk.isomorphism.matchers.Expr.matches(Expr.java:444)
        at org.openscience.cdk.isomorphism.matchers.QueryAtom.matches(QueryAtom.java:763)
        at org.openscience.cdk.isomorphism.AtomMatcher$QueryMatcher.matches(AtomMatcher.java:95)
        at org.openscience.cdk.isomorphism.VFSubState.feasible(VFSubState.java:115)
        at org.openscience.cdk.isomorphism.AbstractVFState.add(AbstractVFState.java:129)
        at org.openscience.cdk.isomorphism.StateStream.map(StateStream.java:108)
        at org.openscience.cdk.isomorphism.StateStream.findNext(StateStream.java:90)
        at org.openscience.cdk.isomorphism.StateStream.<init>(StateStream.java:61)
        at org.openscience.cdk.isomorphism.VentoFoggia$VFIterable.iterator(VentoFoggia.java:252)
        at com.google.common.collect.Iterables.getFirst(Iterables.java:775)
        at org.openscience.cdk.isomorphism.Mappings.first(Mappings.java:508)
        at org.openscience.cdk.smarts.SmartsPattern.match(SmartsPattern.java:136)
        at org.openscience.cdk.isomorphism.Pattern.matches(Pattern.java:117)
        at org.openscience.cdk.fingerprint.MACCSFingerprinter.getBitFingerprint(MACCSFingerprinter.java:145)
        ....
```

**Comment by johnmay** [comment]
No IAtom.bonds() is new...  have you got the code?

**Comment by johnmay** [comment]
i.e. the groovy example. Most likely is the IAtomContainer is created wrongly.

**Comment by egonw** [comment]
https://github.com/egonw/cdkbook/blob/source/code/MACCSFingerprint.groovyin

**Comment by johnmay** [comment]
Replace,  ``new AtomContainer()`` with ``builder.new(IAtomContainer.class)``, or ``builder.newAtomContainer()``.

Will be equivalent next release but currently there is ``AtomContainer`` and ``AtomContainer2`` both are an IAtomContainer, every works providing you use the builders. I kept the old one temporarily but ``AtomContainer2`` will be renamed to ``AtomContainer`` next release.

More info here: https://github.com/cdk/cdk/wiki/AtomContainer2

**Comment by egonw** [comment]
Oh, silly that I didn't think of that :/ So, what about the 2.3 release? Because I doubt I'll be the only one using the `AtomContainer` with the SMARTS matching, instead of the `AtomContainer2`?

**Comment by johnmay** [comment]
If you come from IO (e.g. SMILES/MOLfile) then it will be fine as they all use the builders. The only issue is when you build a molecule from first principles like this.

**Comment by johnmay** [comment]
Can close?
