### ISSUE TITLE
catching InvalidSmilesException class throws NoClassDefFoundError on Java 8

### ISSUE THREAD

**Issue by cartilage-ftw** [cdk/cdk#644]
I'm trying to run a simple code.
```java
import org.openscience.cdk.silent.SilentChemObjectBuilder;
import org.openscience.cdk.smiles.SmilesParser;
import org.openscience.cdk.interfaces.IAtomContainer;
import org.openscience.cdk.exception.InvalidSmilesException;

public class AmbitUtils {

    SmilesParser parser = new SmilesParser(SilentChemObjectBuilder.getInstance());

    public SmilesParser getParser() {
        return parser;
    }

    public void trySomething() {
        try {
            getParser().parseSmiles("CC=O");
        } catch (InvalidSmilesException e) {
            System.out.println("Can't parse given smiles");
            e.printStackTrace();
        }
    }
    public static void main (String[] args) {
        new AmbitUtils().trySomething();
    }
}
```

I compiled this using the terminal using the script.
```bash
javac AmbitUtils.java -cp libs/cdk-2.3.jar:libs/ambit-tautomers-2.0.0-SNAPSHOT.jar
```

where my ```javac -version``` prints ```javac 1.8.0_252```

And running it as ```java AmbitUtils``` throws this
```bash
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/openscience/cdk/exception/InvalidSmilesException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.openscience.cdk.exception.InvalidSmilesException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more
```
I did this on Ubuntu 20.04 LTS, however a friend running the same jdk version on Manjaro 20.0.3 was able to reproduce the exact same error.

Others, please try to see if this is a problem with the JDK version or other JDK versions print the same error.
Any help will be appreciated.

**Comment by cartilage-ftw** [comment]
Update: I tried using JDK 14. Again, it compiled fine but I ran it using ```java AmbitUtils``` it threw the same thing, but in fewer (2) lines
```bash
Error: Unable to initialize main class AmbitUtils
Caused by: java.lang.NoClassDefFoundError: org/openscience/cdk/exception/InvalidSmilesException
```

**Comment by egonw** [comment]
I checked if the class is in the jar:

```shell
$ jar tvf ~/Downloads/cdk-2.3.jar | grep -i invalidsmiles
   728 Fri Aug 09 14:09:16 CEST 2019 org/openscience/cdk/exception/InvalidSmilesException.class
```

**Comment by cartilage-ftw** [comment]
It worked when I tried it in IntelliJ.  I must've made a mistake in the command-line.
Sorry.

**Comment by egonw** [comment]
No worries. I happens to me so often. Happy to hear you solved the problem.
