### ISSUE TITLE
IteratingSMILESReader doesn't handle CxSmiles title correctly

### ISSUE THREAD

**Issue by adalke** [cdk/cdk#702]
The IteratingSMILESReader correctly passes the input line to SmilesParser for processing, which passes the title to CxSmilesParser to see if it contains a cxsmiles. If so, SmilesParser sets the molecule's title so it excludes the cxsmiles. However, the IteratingSMILESReader() then clobbers the (correct) title using a simple line parser which doesn't know about cxsmiles. As a result, the title is incorrect.

This can be fixed by omitting the `setTitle(suffix)` call in IteratingSMILESReader().

Here is a reproducible (in Python, using jpype to connect to CDK built from git commit 41592d883d5f0e1211a51d165efcab61669a6972 (last commit, Thu Dec 31 16:34:07 2020)).

First, a data file with odd-ball coordinates to verify that the cxsmiles is being read correctly:

```
% cat test.smi
CNO |(0.0,0,;1.0,0,;2.0,0,)| benzene
```
(The title 'benzene' is because I forgot to change the title from an earlier, more complex test case.)

Second, a program to parse that file, show the `getTitle()`, and show the molfile; the latter verifies that the cx coordinates are processed:
```
import jpype
import jpype.imports
jpype.startJVM(None, '-Djava.awt.headless=true')
from org.openscience import cdk
import java
fis = java.io.FileInputStream(java.io.File("test.smi"))
reader = cdk.io.iterator.IteratingSMILESReader(fis, cdk.DefaultChemObjectBuilder.getInstance())
mol = reader.next()
print("mol.getTitle() reports:", repr(mol.getTitle()))

writer = cdk.io.SDFWriter(java.lang.System.out)
writer.write(mol)
writer.close()
```

Here's the output:
```
mol.getTitle() reports: '|(0.0,0,;1.0,0,;2.0,0,)| benzene'
|(0.0,0,;1.0,0,;2.0,0,)| benzene
  CDK     01082122012D

  3  2  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0000    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    2.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
M  END
$$$$
```

I believe the relevant code which sets the correct title is in SmilesParser.java at:
```
    private void parseMolCXSMILES(String title, IAtomContainer mol) throws InvalidSmilesException {
        CxSmilesState cxstate;
        int pos;
        if (title != null && title.startsWith("|")) {
            if ((pos = CxSmilesParser.processCx(title, cxstate = new CxSmilesState())) >= 0) {

                // set the correct title
                mol.setTitle(title.substring(pos));
```

This sets the title correctly to skip the cxsmiles component.

The code is called from:
```
    private IAtomContainer parseSmiles(String smiles, boolean isRxnPart) throws InvalidSmilesException {
      ...
            IAtomContainer mol = beamToCDK.toAtomContainer(kekulise ? g.kekule() : g,
                                                           kekulise);
            if (!isRxnPart) {
                try {
                    // CXSMILES layer
                    parseMolCXSMILES(g.getTitle(), mol);
                } catch (Exception e) {
                    e.printStackTrace();
                    throw new InvalidSmilesException("Error parsing CXSMILES:" + e.getMessage());
                }
```

At this point the mol.title is correct because beamToCDK.toAtomContainer() set it, and if there was a cxsmiles then parseMolCXSMILES() updated it.

However, IteratingSMILESReader calls this code as:
```
                final String suffix = suffix(line);

                nextMolecule = readSmiles(line);
                nextMolecule.setTitle(suffix);
```
where readSmiles() does the correct work of setting the title (via SmilesParser):
```
    private IAtomContainer readSmiles(final String line) {
        try {
            return sp.parseSmiles(line);
```
while `setTitle(suffix(line))` clobbers the correct title by simply looking for the first whitespace.

To check, I re-compiled with the following patch:
```
diff --git a/storage/smiles/src/main/java/org/openscience/cdk/io/iterator/IteratingSMILESReader.java b/storage/smiles/src/main/java/org/openscience/cdk/io/iterator/IteratingSMILESReader.java
index b98ace466..bcc419256 100644
--- a/storage/smiles/src/main/java/org/openscience/cdk/io/iterator/IteratingSMILESReader.java
+++ b/storage/smiles/src/main/java/org/openscience/cdk/io/iterator/IteratingSMILESReader.java
@@ -133,7 +133,7 @@ public class IteratingSMILESReader extends DefaultIteratingChemObjectReader<IAto
                 final String suffix = suffix(line);

                 nextMolecule = readSmiles(line);
-                nextMolecule.setTitle(suffix);
+                //nextMolecule.setTitle(suffix);

             } catch (Exception exception) {
                 logger.error("Unexpected problem: ", exception.getMessage());
```
and the output was the expected title of "benzene":
```
% env CLASSPATH=/Users/dalke/cvses/cdk/bundle/target/cdk-2.4-SNAPSHOT.jar python go.py
mol.getTitle() reports: 'benzene'
benzene
  CDK     01082122262D

  3  2  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0000    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    2.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
M  END
$$$$
```

**Comment by johnmay** [comment]
Yep, like I said before the high level readers aren't used much since it's not much more effort to just loop over lines and do what needs to be done. Have made a commit and will check it in with some other bits.

**Comment by adalke** [comment]
"aren't used much"? IteratingSMILESReader seems not uncommon. See the Groovy example at https://ctr.fandom.com/wiki/Ring_counts_in_a_SMILES_file uses  , Rajarshi's rcdk at https://rdrr.io/cran/rcdk/src/R/io.R , Noel's cinfony, and others, like this gist https://gist.github.com/tckb/7b27a4e73c618b05b705 and others.

**Comment by johnmay** [comment]
My biggest gripe with it is how you handle bad molecules in such a API. Do you skip them, stop processing? In this case I think it only recently now returns an empty molecule with an error message. Forcing the user to deal with the iteration removes this problem

**Comment by adalke** [comment]
In chemfp I support an user-specified error handler which is passed to the parser. I provide a few named error handlers: "ignore", "report", and "strict" for the most common cases. Or users can pass in their own handler. As an example, I'll parse a SMILES file with two bad entries, first ignoring any failing records, and second stopping at the first error:

```
% cat bad.smi
NOT_SMILES invalid
CCO valid
NOT_SMILES invalid #2
% python
>>> from chemfp import cdk_toolkit as T
>>> [T.get_id(mol) for mol in T.read_molecules("bad.smi", errors="ignore")]
org.openscience.cdk.io.iterator.IteratingSMILESReader ERROR: Error while reading the SMILES from: NOT_SMILES invalid, org.openscience.cdk.exception.InvalidSmilesException: could not parse 'NOT_SMILES invalid', unexpected character:
org.openscience.cdk.io.iterator.IteratingSMILESReader ERROR: NOT_SMILES invalid
org.openscience.cdk.io.iterator.IteratingSMILESReader ERROR:    ^
org.openscience.cdk.io.iterator.IteratingSMILESReader ERROR: Error while reading the SMILES from: NOT_SMILES invalid #2, org.openscience.cdk.exception.InvalidSmilesException: could not parse 'NOT_SMILES invalid #2', unexpected character:
org.openscience.cdk.io.iterator.IteratingSMILESReader ERROR: NOT_SMILES invalid #2
org.openscience.cdk.io.iterator.IteratingSMILESReader ERROR:    ^
['valid']
>>> [T.get_id(mol) for mol in T.read_molecules("bad.smi", errors="strict")]
org.openscience.cdk.io.iterator.IteratingSMILESReader ERROR: Error while reading the SMILES from: NOT_SMILES invalid, org.openscience.cdk.exception.InvalidSmilesException: could not parse 'NOT_SMILES invalid', unexpected character:
org.openscience.cdk.io.iterator.IteratingSMILESReader ERROR: NOT_SMILES invalid
org.openscience.cdk.io.iterator.IteratingSMILESReader ERROR:    ^
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "/Users/dalke/cvses/cfp-3x/tests/chemfp/base_toolkit.py", line 1121, in <genexpr>
    (mol for (id, mol) in reader),
  File "/Users/dalke/cvses/cfp-3x/tests/chemfp/_cdk_toolkit.py", line 487, in _iter_read_smiles_ids_and_molecules_cdk
    error_handler.error("CDK cannot parse a SMILES record", location)
  File "/Users/dalke/cvses/cfp-3x/tests/chemfp/io.py", line 112, in error
    _compat.raise_tb(ParseError(msg, location), None)
  File "<string>", line 1, in raise_tb
chemfp.ParseError: CDK cannot parse a SMILES record, file 'bad.smi', line 1, record #1: first line is 'NOT_SMILES invalid'
```

If I use "report" then the output is the same as "ignore" except chemfp adds these two lines:

```
ERROR: CDK cannot parse a SMILES record, file 'bad.smi', line 1, record #1: first line is 'NOT_SMILES invalid'. Skipping.
ERROR: CDK cannot parse a SMILES record, file 'bad.smi', line 3, record #3: first line is 'NOT_SMILES invalid #2'. Skipping.
```

Here's what the chemfp/cdk adapter looks like:
```
        while reader.hasNext():
            mol = reader.next()
            recno += 1
            lineno += 1
            if mol.getAtomCount() == 0:
                error_line = mol.getProperty(BAD_SMILES_INPUT)
                if error_line is not None:
                    error_handler.error("CDK cannot parse a SMILES record", location)
                    error_line = None
                    continue
                else:
                    # Empty line. Treat it as a skipped record.
                    recno -= 1
                    continue
```
The location object provides accessor functions for recno, lineno, the current molecule, and potentially a few other fields that the error handler might use.
