### ISSUE TITLE
Possible issue with percieveAtomTypesAndConfigureAtoms()

### ISSUE THREAD

**Issue by Julian-Z98** [cdk/cdk#730]
Hello,

I have a problem with using percieveAtomTypesAndConfigureAtoms(), right after clearAtomConfigurations(). The error only occurs with boron and 4 bonded phosphorus. A NullPointerException is thrown in the CDKAtomTypeMatcher. For phosphorus you get an exception in line 1373 and for boron an exception in line 347. The problems seem to be related to the FormalCharge. If you set this to 0 for the atoms mentioned above (for example in the code tmpBypassError = true), the code works without problems. I have given different example molecules from PubChem for both cases. The CIDs are also given.

```
boolean tmpBypassError = false; //Pass the error or not
SmilesParser tmpParser  = new SmilesParser(DefaultChemObjectBuilder.getInstance());
IAtomContainer tmpMolecule = null;
//P Examples:
tmpMolecule = tmpParser.parseSmiles("C1C2CC3CC1CC(C2)C3(CC(=O)C(=P(C4=CC=CC=C4)(C5=CC=CC=C5)C6=CC=CC=C6)C#N)C7=CC=C(C=C7)F"); //PubChem CID: 89041793
//tmpMolecule = tmpParser.parseSmiles("C1=CC=C(C=C1)C(=O)OCCCC[P+](C2=CC=CC=C2)(C3=CC=CC=C3)C4=CC=CC=C4"); //PubChem CID: 2755300
//tmpMolecule = tmpParser.parseSmiles("C1CCC(=C(C(=P(C2=CC=CC=C2)(C3=CC=CC=C3)C4=CC=CC=C4)C(=O)C(C(F)(F)F)(F)F)C(C(F)(F)F)(F)F)C1"); //PubChem CID: 2752540
//B Ecamples:
//tmpMolecule = tmpParser.parseSmiles("[B-](C1=CC=CC=C1)(C2=CC=CC=C2)(C3=CC=CC=C3)C4=CC=CC=C4"); //PubChem CID: 8934
//tmpMolecule = tmpParser.parseSmiles("[B-]123OC4C(=O)OC(CCC=CC=CCCC(CC(=O)C(C5CCC(C(O1)(O5)C(O2)C(=O)OC(CCC=CC=CCCC(CC(=O)C(C6CCC(C4(O3)O6)(C)O)C)O)C)(C)O)C)O)C"); //PubChem CID: 637168
//tmpMolecule = tmpParser.parseSmiles("[B-]123OC4C(=O)OC5CC(C=CCC(C(C6CCC(C(O1)(O6)C(O2)C(=O)OC7CC(C=CCC(C(C8CCC(C4(O3)O8)C)(C)C)O)OC7C)C)(C)C)O)OC5C"); //PubChem CID: 43587
AtomContainerManipulator.clearAtomConfigurations(tmpMolecule);
if(tmpBypassError) {
    //Avoid the error by setting the FormalCharge to 0
    for(IAtom tmpAtom : tmpMolecule.atoms()) {
        if(tmpAtom.getSymbol() == "B" || (tmpAtom.getSymbol() == "P" && tmpMolecule.getConnectedBondsList(tmpAtom).size() == 4)) {
            tmpAtom.setFormalCharge(0);
        }
    }
}
AtomContainerManipulator.percieveAtomTypesAndConfigureAtoms(tmpMolecule); //Line that causes the error
```

Error Example:
```
java.lang.NullPointerException
	at org.openscience.cdk.atomtype.CDKAtomTypeMatcher.perceivePhosphors(CDKAtomTypeMatcher.java:1373)
	at org.openscience.cdk.atomtype.CDKAtomTypeMatcher.findMatchingAtomType(CDKAtomTypeMatcher.java:141)
	at org.openscience.cdk.atomtype.CDKAtomTypeMatcher.findMatchingAtomType(CDKAtomTypeMatcher.java:122)
	at org.openscience.cdk.tools.manipulator.AtomContainerManipulator.percieveAtomTypesAndConfigureAtoms(AtomContainerManipulator.java:1514)

```
Best reguards,
Julian

**Comment by johnmay** [comment]
Looks like a missing null check, thanks.

Out of interest what were using the atom type perception for?

**Comment by johnmay** [comment]
Actually it looks like the bug is possibly in the calling - clearAtomConfigurations. You shouldn't need to do this for SMILES

**Comment by Julian-Z98** [comment]
Hello John,

Thanks for the quick reply. The SMILES were just an example to show the problem. I need clearAtomConfigurations() and percieveAtomTypesAndConfigureAtoms() for the correct hydrogen saturation with the CDKHydrogenAdder. In the step before, individual atoms are removed from the total molecule, but the hybridisation is not automatically adjusted. Due to the incorrect hybridisation, the CDKHydrogenAdder does not correctly saturate the molecule with hydrogen. The hybridisations of the atoms are reassigned by clear and percieve. 
But I now assign the correct hybridisation to the atoms myself.

Doesn't it speak against an error in clearAtomConfigurations() that in CDKAtomTypeMatcher.perceivePhosphors formalCharge = null was considered for every bond number except 4?

Best reguards,
Julian

**Comment by johnmay** [comment]
Are you coming only from SMILES? The hydrogen are already there you don’t need to add them with the cdk hydrogen adder and that could inadvertently change the formula. The only case you may want this is part of some form of normalisation, which isn’t quite just perceiving atom types. Same is true for molfile and cml (if property set).

My point on the clearAtomTypes was whether it makes sense clear/set a 0 change to null.

**Comment by johnmay** [comment]
Here is clearConfig, despite the documentation it's not quite the "reverseOfPerceiveAtomTypes" in fact I really can't see any use of this unless you want to break you molecules :-). Anyways we've fixed via #732 

```
/**
     * This method will reset all atom configuration to UNSET.
     *
     * This method is the reverse of {@link #percieveAtomTypesAndConfigureAtoms(org.openscience.cdk.interfaces.IAtomContainer)}
     * and after a call to this method all atoms will be "unconfigured".
     *
     * Note that it is not a complete reversal of {@link #percieveAtomTypesAndConfigureAtoms(org.openscience.cdk.interfaces.IAtomContainer)}
     * since the atomic symbol of the atoms remains unchanged. Also, all the flags that were set
     * by the configuration method (such as IS_HYDROGENBOND_ACCEPTOR or ISAROMATIC) will be set to False.
     *
     * @param container The molecule, whose atoms are to be unconfigured
     * @see #percieveAtomTypesAndConfigureAtoms(org.openscience.cdk.interfaces.IAtomContainer)
     */
    public static void clearAtomConfigurations(IAtomContainer container) {
        for (IAtom atom : container.atoms()) {
            atom.setAtomTypeName((String) CDKConstants.UNSET);
            atom.setMaxBondOrder((IBond.Order) CDKConstants.UNSET);
            atom.setBondOrderSum((Double) CDKConstants.UNSET);
            atom.setCovalentRadius((Double) CDKConstants.UNSET);
            atom.setValency((Integer) CDKConstants.UNSET);
            atom.setFormalCharge((Integer) CDKConstants.UNSET);
            atom.setHybridization((IAtomType.Hybridization) CDKConstants.UNSET);
            atom.setFormalNeighbourCount((Integer) CDKConstants.UNSET);
            atom.setFlag(CDKConstants.IS_HYDROGENBOND_ACCEPTOR, false);
            atom.setFlag(CDKConstants.IS_HYDROGENBOND_DONOR, false);
            atom.setProperty(CDKConstants.CHEMICAL_GROUP_CONSTANT, CDKConstants.UNSET);
            atom.setFlag(CDKConstants.ISAROMATIC, false);
            atom.setProperty("org.openscience.cdk.renderer.color", CDKConstants.UNSET);
            atom.setExactMass((Double) CDKConstants.UNSET);
        }
    }
```

**Comment by johnmay** [comment]
To add on, why doesn't clearConfiguration null the atomic number too!  :-)

I guess one could argue that is the fundamental property and everything else is relative but that's not how cheminformatics works, if we have the info we want to preserve it.

**Comment by Julian-Z98** [comment]
In the actual application, the molecules are loaded from a molfile and are then changed. Since some atoms were removed from the total molecule, hydrogens must be added to the IAtomContainer. But since the hybridisation was not adjusted during the removal, the correct number of hydrogens is not added by the CDKHydrogenAdder.

clear/set was only an attempt to automatically reset the hybridisation. In fact, apart from the previously mentioned exceptions, this worked for all molecules without losing any information that was needed.  I am aware that this is not the actual purpose of this method and that this solution is not useful in most cases.

Thank you for the quick clarification.

**Comment by johnmay** [comment]
When doing such things the more efficient and correct thing to do is to increment the hydrogen counts on either end by the bond order being removed.

For example:
```
IAtomContainer mol = "CCO";
IBond bond = mol.getBond(1); // -CH2-OH bond
IAtom beg = bond.getBegin();
IAtom end = bond.getEnd();
mol.removeBond(bond); 
// SMILES=C[CH2].[OH]
beg.setImplicitHydrogenCount(beg.getImplicitHydrogenCount()+bond.getOrder());
end.setImplicitHydrogenCount(end.getImplicitHydrogenCount()+bond.getOrder());
// SMILES=C[CH3].O
```

**Comment by Julian-Z98** [comment]
Thank you for the suggestion. I will keep that in mind. At the moment, however, it works very well if I only clear the hybridisation. This is also unproblematic in terms of speed.

`atom.setHybridization((IAtomType.Hybridization) CDKConstants.UNSET);`
