### ISSUE TITLE
@aws-cdk/cloudformation-include fails when include a valid template

### ISSUE THREAD

**Issue by mcuervoe** [cdk/cdk#757]
The following code fails when I try to include the cloudformation template provided by atomic (which works correctly when use directly with cloudformation)

````typescript
import * as cdk from '@aws-cdk/core';
import * as cfninc from '@aws-cdk/cloudformation-include';

export class CdkTest2Stack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // The code that defines your stack goes here
    const template = new cfninc.CfnInclude(this, 'Template', {
      templateFile: 'datomic-compute-936-9118.json',
    });
  }
}
```` 

The error that I get is

```bash
$ cdk ls
Invalid tag input expected {key, value, propagateAtLaunch} have "<unresolved-token>"

/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/aws-autoscaling/lib/autoscaling.generated.ts:381
            tags: this.tags.renderTags(),
                            ^
While synthesizing CdkTest2Stack/Template/TxAutoScalingGroup: Cannot read property 'renderTags' of undefined
  --- resource created at ---
  at Function._fromCloudFormation (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/aws-autoscaling/lib/autoscaling.generated.ts:231:21)
  at CfnInclude.getOrCreateResource (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/lib/cfn-include.ts:519:40)
  at Object.findResource (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/lib/cfn-include.ts:487:21)
  at Object.findRefTarget (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/lib/cfn-include.ts:495:21)
  at CfnParser.parseIfCfnIntrinsic (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:523:42)
  at CfnParser.parseValue (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:494:33)
  at /home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:490:38
  at Array.map (<anonymous>)
  at CfnParser.parseValue (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:490:23)
  at CfnParser.parseValue (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:500:25)
  at Function._fromCloudFormation (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/aws-codedeploy/lib/codedeploy.generated.ts:692:51)
  at CfnInclude.getOrCreateResource (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/lib/cfn-include.ts:519:40)
  at Object.findResource (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/lib/cfn-include.ts:487:21)
  at Object.findRefTarget (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/lib/cfn-include.ts:495:21)
  at go (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:741:40)
  at go (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:711:52)
  at go (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:734:42)
  at go (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:734:42)
  at CfnParser.parseFnSubString (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:686:19)
  at CfnParser.parseIfCfnIntrinsic (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:649:21)
  at CfnParser.parseValue (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:494:33)
  at /home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:490:38
  at Array.map (<anonymous>)
  at CfnParser.parseValue (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:490:23)
  at CfnParser.parseValue (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:500:25)
  at /home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:490:38
  at Array.map (<anonymous>)
  at CfnParser.parseValue (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:490:23)
  at CfnParser.parseValue (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:500:25)
  at CfnParser.parseValue (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:500:25)
  at Function._fromCloudFormation (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/aws-iam/lib/iam.generated.ts:881:51)
  at CfnInclude.getOrCreateResource (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/lib/cfn-include.ts:519:40)
  at Object.findResource (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/lib/cfn-include.ts:487:21)
  at CfnParser.handleAttributes (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:375:39)
  at Function._fromCloudFormation (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/aws-lambda/lib/lambda.generated.ts:1702:24)
  at CfnInclude.getOrCreateResource (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/lib/cfn-include.ts:519:40)
  at Object.findResource (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/lib/cfn-include.ts:487:21)
  at CfnParser.parseIfCfnIntrinsic (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:549:36)
  at CfnParser.parseValue (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:494:33)
  at CfnParser.parseValue (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:500:25)
  at /home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:490:38
  at Array.map (<anonymous>)
  at CfnParser.parseValue (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:490:23)
  at CfnParser.parseIfCfnIntrinsic (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:638:28)
  at CfnParser.parseValue (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:494:33)
  at CfnParser.parseValue (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/node_modules/@aws-cdk/core/lib/cfn-parse.ts:500:25)
  at Function._fromCloudFormation (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/aws-stepfunctions/lib/stepfunctions.generated.ts:315:51)
  at CfnInclude.getOrCreateResource (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/lib/cfn-include.ts:519:40)
  at new CfnInclude (/home/miguel/git/compnsate/cdk-test2/node_modules/@aws-cdk/cloudformation-include/lib/cfn-include.ts:97:12)
  at new CdkTest2Stack (/home/miguel/git/compnsate/cdk-test2/lib/cdk-test2-stack.ts:9:22)
  at Object.<anonymous> (/home/miguel/git/compnsate/cdk-test2/bin/cdk-test2.ts:7:1)
  at Module._compile (internal/modules/cjs/loader.js:999:30)
  at Module.m._compile (/home/miguel/git/compnsate/cdk-test2/node_modules/ts-node/src/index.ts:1056:23)
  at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
  at Object.require.extensions.<computed> [as .ts] (/home/miguel/git/compnsate/cdk-test2/node_modules/ts-node/src/index.ts:1059:12)
```

The template can be
 found here https://s3.amazonaws.com/datomic-cloud-1/cft/936-9118/datomic-compute-936-9118.json
 or in the document attached 

[datomic-compute-936-9118.zip](https://github.com/cdk/cdk/files/7310779/datomic-compute-936-9118.zip)

**Comment by johnmay** [comment]
Hi, I think you have the wrong project this a library for chemistry. 

You want this one: https://github.com/aws/aws-cdk
