### ISSUE TITLE
Regression: Inchi to Structure generate coordinates throws NullPointerException

### ISSUE THREAD

**Issue by dkatzel-ncats** [cdk/cdk#796]
when using `InChIGeneratorFactory` to create an `IAtomContainer` from an Inchi and then asking to generate coordinates now throws a NullPointerException.  This worked in CDK 2.6 before the migration to JNA-Inchi

Example code that fails
```java
//randomly chosen CHEMBL id: CHEMBL444987
InChIToStructure parser = InChIGeneratorFactory.getInstance().getInChIToStructure(
                "InChI=1S/C16H25NO/c1-14(2)8-6-9-15(3)10-7-11-16(18)17-12-4-5-13-17/h7-8,10-11H,4-6,9,12-13H2,1-3H3/b11-7+,15-10+",
                DefaultChemObjectBuilder.getInstance(), new ArrayList<>());

StructureDiagramGenerator coordinateGenerator = new StructureDiagramGenerator(parser.getAtomContainer());
coordinateGenerator.generateCoordinates();
```

Will throw an exception on the call to generateCoordinates() with the following NPE        

```
Caused by: java.lang.NullPointerException
	at org.openscience.cdk.layout.CorrectGeometricConfiguration.parity(CorrectGeometricConfiguration.java:261)
	at org.openscience.cdk.layout.CorrectGeometricConfiguration.adjust(CorrectGeometricConfiguration.java:138)
	at org.openscience.cdk.layout.CorrectGeometricConfiguration.<init>(CorrectGeometricConfiguration.java:117)
	at org.openscience.cdk.layout.CorrectGeometricConfiguration.<init>(CorrectGeometricConfiguration.java:92)
	at org.openscience.cdk.layout.CorrectGeometricConfiguration.correct(CorrectGeometricConfiguration.java:81)
	at org.openscience.cdk.layout.StructureDiagramGenerator.generateCoordinates(StructureDiagramGenerator.java:694)
	at org.openscience.cdk.layout.StructureDiagramGenerator.generateCoordinates(StructureDiagramGenerator.java:606)
	at org.openscience.cdk.layout.StructureDiagramGenerator.generateCoordinates(StructureDiagramGenerator.java:1578)
```

**Comment by johnmay** [comment]
Thanks should be an easy fix, will do a 2.7.1 release once resolved since there was another issue with moving to jna inchi.

**Comment by johnmay** [comment]
Fixed - nothing to do with JNA inchi but rather when I added the check for extended cis trans I removed the logic to correct the bond storage order. https://github.com/cdk/cdk/commit/60a559e0bac12667ed48627c02cdf391e16eb03d

@egonw I pushed this directly as going to do a 2.7.1 release now.

**Comment by dkatzel-ncats** [comment]
thanks! this does fix this issue. closing
