### ISSUE TITLE
SmilesGenerator still depends on JNI inchi when generating Absolute SMILES

### ISSUE THREAD

**Issue by dkatzel-ncats** [cdk/cdk#797]
after switching to JNA inchi, there is still a dependency to the old jni inchi in `org.openscience.cdk.smiles.SmilesGenerator.#inchiNumbers` method which dynamically loads the class `org.openscience.cdk.graph.invariant.InChINumbersTools` which imports classes from the inchi package.  If you don't still have the old jni inchi class on your classpath (which has log4j vulnerabilities) then the code will error out with 

```
java.lang.NoClassDefFoundError: [Lnet/sf/jniinchi/INCHI_OPTION;

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at org.openscience.cdk.smiles.SmilesGenerator.inchiNumbers(SmilesGenerator.java:715)
	at org.openscience.cdk.smiles.SmilesGenerator.labels(SmilesGenerator.java:681)
```

**Comment by johnmay** [comment]
Now fixed
