### ISSUE TITLE
Javadoc needs update

### ISSUE THREAD

**Issue by RamiManaf** [cdk/cdk#869]
The javadoc description in the `AtomTypeMapper.getInstance(String mappingFile)` refers to a file named `org.openscience.cdk.config.data.cdk-sybyl-mappings.owl` while the location of types mapper files had changed to `org.openscience.cdk.dict.data`
https://github.com/cdk/cdk/blob/b12da73d5d70cafa7c00404d5b576c6f8b33e124/base/atomtype/src/main/java/org/openscience/cdk/atomtype/mapper/AtomTypeMapper.java#L59
Moreover, The following code won't work anymore and I think it's probably because the mapping file is in another jar?
`AtomTypeMapper.getInstance(("/org/openscience/cdk/dict/data/cdk-sybyl-mappings.owl"));`
<pre>java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.openscience.cdk.atomtype.mapper.AtomTypeMapper.<init>(AtomTypeMapper.java:47)
	at org.openscience.cdk.atomtype.mapper.AtomTypeMapper.getInstance(AtomTypeMapper.java:67)</pre>
However, resolving the resource from my code resolved the problem.
`AtomTypeMapper.getInstance("cdk-sybyl-mappings.owl", getClass().getResourceAsStream("/org/openscience/cdk/dict/data/cdk-sybyl-mappings.owl"));`

**Comment by egonw** [comment]
Sounds like a bug. I'll look into is as soon as possible.

**Comment by johnmay** [comment]
You edited but the issue with the getInstance() was the leading slash.

```
AtomTypeMapper mapper = AtomTypeMapper.getInstance("/org/openscience/cdk/dict/data/cdk-sybyl-mappings.owl"); // wrong
AtomTypeMapper mapper = AtomTypeMapper.getInstance("org/openscience/cdk/dict/data/cdk-sybyl-mappings.owl"); // right
```
Fixed now:
https://github.com/cdk/cdk/commit/1ec62a3c7c8a1aa130a8ea2986098469aa3ab204
