### ISSUE TITLE
Fix Taglets

### ISSUE THREAD

**Issue by johnmay** [cdk/cdk#908]
I may actually put the build-utils as an orphan module of the project.

```
org.apache.maven.reporting.MavenReportException:
Exit code: 1 - javadoc: error - In doclet class com.sun.tools.doclets.standard.Standard,  method start has thrown an exception java.lang.reflect.InvocationTargetException
java.lang.NoClassDefFoundError: nu/xom/Node
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
```

**Comment by johnmay** [comment]
Done, some issues with @cdk.githash and @cdk.iooptions - but these sort of work OK.
