### ISSUE TITLE
ArrayOutOfBoundsException at org.openscience.cdk.graph.InitialCycles

### ISSUE THREAD

**Issue by uli-f** [cdk/cdk#929]
I am not sure if this is another case of gigo (garbage in, garbage out) or an actual bug.

Whichever it is, avoiding a runtime exception - an `ArrayOutOfBoundsException` in this case - might still be desirable.

Here is the code that gives raise to the exception:

```
class AromaticityToolsTest {

    @Test
    void testAssignDaylightAromaticity_atomContainer_arrayIndexOutOfBoundsWrappedInCDKException() throws CDKException, IOException {
        // arrange
        final String molfile = """
                                
                  Mrv2216 11082213292D         \s
                                
                100141  0  0  0  0            999 V2000
                   -8.6190   -3.1025    0.0000 C   0  0  0  0  0  0  0  0  0  1  0  0
                   -8.5666   -3.8644    0.0000 C   0  0  0  0  0  0  0  0  0  2  0  0
                   -7.9024   -3.6013    0.0000 C   0  0  0  0  0  0  0  0  0  3  0  0
                   -6.9824   -3.2635    0.0000 C   0  0  0  0  0  0  0  0  0  4  0  0
                   -7.0657   -2.4098    0.0000 C   0  0  0  0  0  0  0  0  0  5  0  0
                   -7.7932   -2.3674    0.0000 C   0  0  0  0  0  0  0  0  0  6  0  0
                   -7.1273   -1.7694    0.0000 C   0  0  0  0  0  0  0  0  0  7  0  0
                   -7.2382   -2.8192    0.0000 C   0  0  0  0  0  0  0  0  0  8  0  0
                   -6.4305   -3.4436    0.0000 C   0  0  0  0  0  0  0  0  0  9  0  0
                   -5.6769   -3.1011    0.0000 C   0  0  0  0  0  0  0  0  0 10  0  0
                   -6.4363   -2.9038    0.0000 C   0  0  0  0  0  0  0  0  0 11  0  0
                   -7.2862   -3.5542    0.0000 C   0  0  0  0  0  0  0  0  0 12  0  0
                   -7.9860   -3.0167    0.0000 C   0  0  0  0  0  0  0  0  0 13  0  0
                   -8.3752   -2.1287    0.0000 C   0  0  0  0  0  0  0  0  0 14  0  0
                   -7.5718   -1.5686    0.0000 C   0  0  0  0  0  0  0  0  0 15  0  0
                   -6.6509   -1.9439    0.0000 C   0  0  0  0  0  0  0  0  0 16  0  0
                   -5.8652   -1.2690    0.0000 C   0  0  0  0  0  0  0  0  0 17  0  0
                   -5.9812   -0.4169    0.0000 C   0  0  0  0  0  0  0  0  0 18  0  0
                   -5.3048    0.3066    0.0000 C   0  0  0  0  0  0  0  0  0 19  0  0
                   -5.1670    1.1272    0.0000 C   0  0  0  0  0  0  0  0  0 20  0  0
                   -5.8952    1.2978    0.0000 C   0  0  0  0  0  0  0  0  0100  0  0
                   -6.5373    0.6798    0.0000 C   0  0  0  0  0  0  0  0  0 21  0  0
                   -6.6236   -0.2565    0.0000 C   0  0  0  0  0  0  0  0  0 22  0  0
                   -7.4079   -0.8373    0.0000 C   0  0  0  0  0  0  0  0  0 23  0  0
                   -7.9531   -0.3306    0.0000 C   0  0  0  0  0  0  0  0  0 24  0  0
                   -7.8591    0.4672    0.0000 C   0  0  0  0  0  0  0  0  0 25  0  0
                   -7.0976    1.0252    0.0000 C   0  0  0  0  0  0  0  0  0 26  0  0
                   -7.5019    1.8805    0.0000 C   0  0  0  0  0  0  0  0  0 27  0  0
                   -6.8826    1.4797    0.0000 C   0  0  0  0  0  0  0  0  0 28  0  0
                   -7.3168    0.6339    0.0000 C   0  0  0  0  0  0  0  0  0 29  0  0
                   -8.2240    1.0446    0.0000 C   0  0  0  0  0  0  0  0  0 30  0  0
                   -8.8322    0.5434    0.0000 C   0  0  0  0  0  0  0  0  0 31  0  0
                   -9.4792    0.1803    0.0000 C   0  0  0  0  0  0  0  0  0 32  0  0
                   -8.9046   -0.5381    0.0000 C   0  0  0  0  0  0  0  0  0 33  0  0
                   -9.1057   -1.4631    0.0000 C   0  0  0  0  0  0  0  0  0 34  0  0
                  -10.0641   -1.4801    0.0000 C   0  0  0  0  0  0  0  0  0 35  0  0
                  -10.5992   -0.8749    0.0000 C   0  0  0  0  0  0  0  0  0 36  0  0
                  -10.0909   -0.2683    0.0000 C   0  0  0  0  0  0  0  0  0 37  0  0
                   -9.5667   -1.0951    0.0000 C   0  0  0  0  0  0  0  0  0 38  0  0
                   -9.8151   -2.0119    0.0000 C   0  0  0  0  0  0  0  0  0 39  0  0
                   -9.3685   -2.6866    0.0000 C   0  0  0  0  0  0  0  0  0 40  0  0
                   -8.4870   -2.6602    0.0000 C   0  0  0  0  0  0  0  0  0 41  0  0
                   -8.1614   -1.7937    0.0000 C   0  0  0  0  0  0  0  0  0 42  0  0
                   -8.6594   -1.1028    0.0000 C   0  0  0  0  0  0  0  0  0 43  0  0
                   -8.3634   -0.3290    0.0000 C   0  0  0  0  0  0  0  0  0 44  0  0
                   -7.3271   -0.4348    0.0000 C   0  0  0  0  0  0  0  0  0 45  0  0
                   -6.8679    0.1161    0.0000 C   0  0  0  0  0  0  0  0  0 46  0  0
                   -5.9654    0.0516    0.0000 C   0  0  0  0  0  0  0  0  0 47  0  0
                   -5.4842   -0.8970    0.0000 C   0  0  0  0  0  0  0  0  0 48  0  0
                   -4.6371   -1.0917    0.0000 C   0  0  0  0  0  0  0  0  0 49  0  0
                   -4.0957   -2.0507    0.0000 C   0  0  0  0  0  0  0  0  0 50  0  0
                   -3.9791   -2.6346    0.0000 C   0  0  0  0  0  0  0  0  0 51  0  0
                   -5.0181   -2.6704    0.0000 C   0  0  0  0  0  0  0  0  0 52  0  0
                   -5.7093   -1.7187    0.0000 C   0  0  0  0  0  0  0  0  0 53  0  0
                   -6.8050   -1.2951    0.0000 C   0  0  0  0  0  0  0  0  0 54  0  0
                   -7.3780   -2.0185    0.0000 C   0  0  0  0  0  0  0  0  0 55  0  0
                   -6.7490   -2.6493    0.0000 C   0  0  0  0  0  0  0  0  0 56  0  0
                   -5.7570   -2.5865    0.0000 C   0  0  0  0  0  0  0  0  0 57  0  0
                   -5.1866   -2.0320    0.0000 C   0  0  0  0  0  0  0  0  0 58  0  0
                   -6.0327   -1.9725    0.0000 C   0  0  0  0  0  0  0  0  0 59  0  0
                   -6.1381   -0.9615    0.0000 C   0  0  0  0  0  0  0  0  0 60  0  0
                   -6.2399   -1.6068    0.0000 C   0  0  0  0  0  0  0  0  0 61  0  0
                   -5.4736   -2.2278    0.0000 C   0  0  0  0  0  0  0  0  0 62  0  0
                   -5.0804   -1.3937    0.0000 C   0  0  0  0  0  0  0  0  0 63  0  0
                   -5.1269   -0.2320    0.0000 C   0  0  0  0  0  0  0  0  0 64  0  0
                   -4.6483    0.2038    0.0000 C   0  0  0  0  0  0  0  0  0 65  0  0
                   -3.9108    0.4233    0.0000 C   0  0  0  0  0  0  0  0  0 66  0  0
                   -3.6491    1.0960    0.0000 C   0  0  0  0  0  0  0  0  0 67  0  0
                   -4.3093    1.5769    0.0000 C   0  0  0  0  0  0  0  0  0 68  0  0
                   -4.3830    2.3983    0.0000 C   0  0  0  0  0  0  0  0  0 69  0  0
                   -3.5137    2.6037    0.0000 C   0  0  0  0  0  0  0  0  0 70  0  0
                   -2.8293    2.0455    0.0000 C   0  0  0  0  0  0  0  0  0 71  0  0
                   -2.8358    1.1565    0.0000 C   0  0  0  0  0  0  0  0  0 72  0  0
                   -2.3720    0.2664    0.0000 C   0  0  0  0  0  0  0  0  0 73  0  0
                   -1.6621   -0.2777    0.0000 C   0  0  0  0  0  0  0  0  0 74  0  0
                   -1.6500   -1.1735    0.0000 C   0  0  0  0  0  0  0  0  0 75  0  0
                   -2.3642   -1.7451    0.0000 C   0  0  0  0  0  0  0  0  0 76  0  0
                   -3.0393   -2.4692    0.0000 C   0  0  0  0  0  0  0  0  0 77  0  0
                   -2.9362   -1.6867    0.0000 C   0  0  0  0  0  0  0  0  0 78  0  0
                   -3.4027   -0.8230    0.0000 C   0  0  0  0  0  0  0  0  0 79  0  0
                   -4.2270   -0.3415    0.0000 C   0  0  0  0  0  0  0  0  0 80  0  0
                   -4.7486    0.7023    0.0000 C   0  0  0  0  0  0  0  0  0 81  0  0
                   -5.6379    0.7780    0.0000 C   0  0  0  0  0  0  0  0  0 82  0  0
                   -6.1614    1.6374    0.0000 C   0  0  0  0  0  0  0  0  0 83  0  0
                   -5.9179    2.5534    0.0000 C   0  0  0  0  0  0  0  0  0 84  0  0
                   -5.0854    2.2967    0.0000 C   0  0  0  0  0  0  0  0  0 85  0  0
                   -4.7470    1.5706    0.0000 C   0  0  0  0  0  0  0  0  0 86  0  0
                   -6.7367    3.1545    0.0000 C   0  0  0  0  0  0  0  0  0 87  0  0
                   -7.0227    2.5401    0.0000 C   0  0  0  0  0  0  0  0  0 88  0  0
                   -6.1085    2.1722    0.0000 C   0  0  0  0  0  0  0  0  0 89  0  0
                   -5.3132    2.7739    0.0000 C   0  0  0  0  0  0  0  0  0 90  0  0
                   -5.5332    3.5949    0.0000 C   0  0  0  0  0  0  0  0  0 91  0  0
                   -6.3119    3.8644    0.0000 C   0  0  0  0  0  0  0  0  0 92  0  0
                   -2.8937   -1.1712    0.0000 C   0  0  0  0  0  0  0  0  0 93  0  0
                   -2.9029   -0.3431    0.0000 C   0  0  0  0  0  0  0  0  0 94  0  0
                   -3.6374   -0.2281    0.0000 C   0  0  0  0  0  0  0  0  0 95  0  0
                   -4.2560   -0.8690    0.0000 C   0  0  0  0  0  0  0  0  0 96  0  0
                   -5.0642   -0.7021    0.0000 C   0  0  0  0  0  0  0  0  0 97  0  0
                   -4.3700   -1.5307    0.0000 C   0  0  0  0  0  0  0  0  0 98  0  0
                   -3.6867   -1.5312    0.0000 C   0  0  0  0  0  0  0  0  0 99  0  0
                  1  2  2  0  0  0  0
                  1  6  1  0  0  0  0
                  2  3  1  0  0  0  0
                  3  4  1  0  0  0  0
                  3 42  2  0  0  0  0
                  4  5  1  0  0  0  0
                  4 57  2  0  0  0  0
                  5  6  2  0  0  0  0
                  5 60  1  0  0  0  0
                  6  7  1  0  0  0  0
                  7  8  2  0  0  0  0
                  7 62  1  0  0  0  0
                  8  9  1  0  0  0  0
                  9 10  2  0  0  0  0
                 10 11  1  0  0  0  0
                 10 63  1  0  0  0  0
                 11 12  1  0  0  0  0
                 11 16  2  0  0  0  0
                 12 13  2  0  0  0  0
                 13 14  1  0  0  0  0
                 14 15  2  0  0  0  0
                 14 35  1  0  0  0  0
                 15 16  1  0  0  0  0
                 15 24  1  0  0  0  0
                 16 17  1  0  0  0  0
                 17 18  1  0  0  0  0
                 17 64  2  0  0  0  0
                 18 19  1  0  0  0  0
                 18 23  2  0  0  0  0
                 19 20  1  0  0  0  0
                 19 66  2  0  0  0  0
                 20 21  2  0  0  0  0
                 20 69  1  0  0  0  0
                 21 22  1  0  0  0  0
                 21 90  1  0  0  0  0
                 22 23  1  0  0  0  0
                 22 27  2  0  0  0  0
                 23 24  1  0  0  0  0
                 24 25  2  0  0  0  0
                 25 26  1  0  0  0  0
                 25 34  1  0  0  0  0
                 26 27  1  0  0  0  0
                 26 31  2  0  0  0  0
                 27 28  1  0  0  0  0
                 28 29  2  0  0  0  0
                 28 89  1  0  0  0  0
                 29 30  1  0  0  0  0
                 29 84  1  0  0  0  0
                 30 31  1  0  0  0  0
                 30 47  2  0  0  0  0
                 31 32  1  0  0  0  0
                 32 33  1  0  0  0  0
                 32 45  2  0  0  0  0
                 33 34  2  0  0  0  0
                 33 38  1  0  0  0  0
                 34 35  1  0  0  0  0
                 35 36  2  0  0  0  0
                 36 37  1  0  0  0  0
                 37 38  2  0  0  0  0
                 38 39  1  0  0  0  0
                 39 40  1  0  0  0  0
                 39 44  2  0  0  0  0
                 40 41  2  0  0  0  0
                 41 42  1  0  0  0  0
                 42 43  1  0  0  0  0
                 43 44  1  0  0  0  0
                 43 56  2  0  0  0  0
                 44 45  1  0  0  0  0
                 45 46  1  0  0  0  0
                 46 47  1  0  0  0  0
                 46 55  2  0  0  0  0
                 47 48  1  0  0  0  0
                 48 49  2  0  0  0  0
                 48 83  1  0  0  0  0
                 49 50  1  0  0  0  0
                 49 54  1  0  0  0  0
                 50 51  1  0  0  0  0
                 50 81  1  0  0  0  0
                 51 52  2  0  0  0  0
                 51100  1  0  0  0  0
                 52 53  1  0  0  0  0
                 52 78  1  0  0  0  0
                 53 54  2  0  0  0  0
                 53 58  1  0  0  0  0
                 54 55  1  0  0  0  0
                 54 58  1  0  0  0  0
                 55 56  1  0  0  0  0
                 56 57  1  0  0  0  0
                 57 58  1  0  0  0  0
                 58 59  1  0  0  0  0
                 59 60  1  0  0  0  0
                 59 99  1  0  0  0  0
                 60 61  2  0  0  0  0
                 61 62  1  0  0  0  0
                 61 98  1  0  0  0  0
                 62 63  2  0  0  0  0
                 63 64  1  0  0  0  0
                 64 65  1  0  0  0  0
                 65 66  1  0  0  0  0
                 65 98  2  0  0  0  0
                 66 67  1  0  0  0  0
                 67 68  1  0  0  0  0
                 67 96  2  0  0  0  0
                 68 69  2  0  0  0  0
                 68 73  1  0  0  0  0
                 69 70  1  0  0  0  0
                 70 71  2  0  0  0  0
                 70 91  1  0  0  0  0
                 71 72  1  0  0  0  0
                 72 73  2  0  0  0  0
                 73 74  1  0  0  0  0
                 74 75  1  0  0  0  0
                 74 95  2  0  0  0  0
                 75 76  2  0  0  0  0
                 76 77  1  0  0  0  0
                 77 78  1  0  0  0  0
                 77 94  2  0  0  0  0
                 78 79  2  0  0  0  0
                 79 80  1  0  0  0  0
                 80 81  2  0  0  0  0
                 81 82  1  0  0  0  0
                 82 83  1  0  0  0  0
                 82 87  2  0  0  0  0
                 83 84  2  0  0  0  0
                 84 85  1  0  0  0  0
                 85 86  2  0  0  0  0
                 85 88  1  0  0  0  0
                 86 87  1  0  0  0  0
                 88 89  2  0  0  0  0
                 88 93  1  0  0  0  0
                 89 90  1  0  0  0  0
                 90 91  2  0  0  0  0
                 91 92  1  0  0  0  0
                 92 93  2  0  0  0  0
                 94 95  1  0  0  0  0
                 94100  1  0  0  0  0
                 95 96  1  0  0  0  0
                 96 97  1  0  0  0  0
                 97 98  1  0  0  0  0
                 97 99  2  0  0  0  0
                 99100  1  0  0  0  0
                M  END
                """;

        final MDLV2000Reader mdlv2000Reader = new MDLV2000Reader(new StringReader(molfile));
        final IAtomContainer atomContainer = mdlv2000Reader.read(DefaultChemObjectBuilder.getInstance().newAtomContainer());
        Aromaticity aromaticity = new Aromaticity(ElectronDonation.daylight(), Cycles.or(Cycles.all(), Cycles.essential()));

        // act
        aromaticity.apply(atomContainer);

        // tear down
        mdlv2000Reader.close();
    }
}
```

This is the top of the stack trace:
```
Index 5 out of bounds for length 5
java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
	at org.openscience.cdk.graph.InitialCycles$EvenCycle.family(InitialCycles.java:603)
	at org.openscience.cdk.graph.RelevantCycles.paths(RelevantCycles.java:159)
	at org.openscience.cdk.graph.EssentialCycles.groupByLength(EssentialCycles.java:140)
	at org.openscience.cdk.graph.EssentialCycles.<init>(EssentialCycles.java:104)
	at org.openscience.cdk.graph.Cycles$CycleComputation$2.apply(Cycles.java:732)
	at org.openscience.cdk.graph.Cycles$CycleComputation.find(Cycles.java:883)
	at org.openscience.cdk.graph.Cycles$Fallback.find(Cycles.java:1084)
	at org.openscience.cdk.aromaticity.Aromaticity.findBonds(Aromaticity.java:200)
	at org.openscience.cdk.aromaticity.Aromaticity.apply(Aromaticity.java:238)
```

I am note sure if wrapping up the molecule in Daylight aromaticity when it originated from the `MDLV2000Reader` is a great idea. And the problem _does_ go away if the CycleFinder is called on its own:

```
CycleFinder cycleFinder = Cycles.or(Cycles.all(), Cycles.essential());
cycleFinder.find(atomContainer);
```

Here is a depiction of the molecule which doesn't look too healthy with its pentavalent carbon:

![image](https://user-images.githubusercontent.com/98144814/200791843-c053269a-35bf-4355-910e-7d19900a966f.png)

Please let me know if there is anything else you need from my side in case you want to investigate.

**Comment by johnmay** [comment]
Yep we'll add a test, the only thing it might be is if there is a loop or
multi-edge, C1C1 in SMILES for example is diss-allowed but we don't do such
checks in a MOLfile.

John

**Comment by johnmay** [comment]
I think I see what's going on but it's a hard fix which needs some thought.

**Comment by uli-f** [comment]
Thanks for the feedback!

I calculated the cycles for millions of molecules and this is the first time I experienced an issue. I am very happy with the functionality and speed when it comes to the computation of cycles in CDK 😃

**Comment by johnmay** [comment]
This molecule is a little broken (some of the carbons are missing a double bond) but that should cause a problem. Indeed if we pass the molecule directly into the Cycles API all is fine. It's some complex interaction with how the aromaticity creates subgraphs/subsets.

**Comment by johnmay** [comment]
OK I'm amazed that went unnoticed for so long. Basically an obvious omission in the BFS/shortest-path finding code, or rather a specialisation of it which takes a permutation of the vertices and only gives you paths that are lexicographically descending. Some bonkers PhD student wrote this years ago (me) and I had to relearn what was going on.

**Comment by uli-f** [comment]
@johnmay Do you want me add the test case [above](https://github.com/cdk/cdk/issues/929#issue-1441758542) to CyclesTest?

**Comment by johnmay** [comment]
I think it’s ok. That example didn’t really help pin it down - a better test would be on the shortest paths api. It is pretty hard to craft and input which triggers it though
