### ISSUE TITLE
javadoc taglet issue

### ISSUE THREAD

**Issue by uli-f** [cdk/cdk#931]
I added some javadoc and tried to generate the javadoc to validate that everything is fine.

However, when executing `javadoc:aggregate` I run into the following error:

```
error: An internal exception has occurred. 
  	(java.lang.NoClassDefFoundError: org/xmlcml/cml/element/CMLMolecule)
Please file a bug against the javadoc tool via the Java bug reporting page
(http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com)
for duplicates. Include error messages and the following diagnostic in your report. Thank you.
java.lang.NoClassDefFoundError: org/xmlcml/cml/element/CMLMolecule
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at net.sf.cdk.tools.doclets.CDKIOOptionsTaglet.toString(CDKIOOptionsTaglet.java:89)
	at net.sf.cdk.tools.doclets.CDKIOOptionsTaglet.toString(CDKIOOptionsTaglet.java:130)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.taglets.UserTaglet.getAllBlockTagOutput(UserTaglet.java:125)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.taglets.TagletWriter.getBlockTagOutput(TagletWriter.java:288)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDocletWriter.getBlockTagOutput(HtmlDocletWriter.java:365)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDocletWriter.getBlockTagOutput(HtmlDocletWriter.java:351)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDocletWriter.addTagsInfo(HtmlDocletWriter.java:337)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.ClassWriterImpl.addClassTagInfo(ClassWriterImpl.java:224)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.builders.ClassBuilder.buildClassTagInfo(ClassBuilder.java:316)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.builders.ClassBuilder.buildClassInfo(ClassBuilder.java:185)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.builders.ClassBuilder.buildClassDoc(ClassBuilder.java:147)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.builders.ClassBuilder.build(ClassBuilder.java:113)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDoclet.generateClassFiles(HtmlDoclet.java:388)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.AbstractDoclet.generateClassFiles(AbstractDoclet.java:286)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDoclet.generateClassFiles(HtmlDoclet.java:199)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.AbstractDoclet.startGeneration(AbstractDoclet.java:212)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.AbstractDoclet.run(AbstractDoclet.java:115)
	at jdk.javadoc/jdk.javadoc.doclet.StandardDoclet.run(StandardDoclet.java:103)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:556)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:393)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:342)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
Caused by: java.lang.ClassNotFoundException: org.xmlcml.cml.element.CMLMolecule
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 25 more
5 errors
100 warnings

Command line was: cmd.exe /X /C ""C:\Program Files\Eclipse Adoptium\jdk-17.0.4.101-hotspot\bin\javadoc.exe" @options @packages"
```

There is a warning earlier on that might be related:

```
[WARNING] The POM for org.openscience.cdk:cdk-smiles:jar:2.8-20220912.161903-40 is missing, no dependency information available
[WARNING] The POM for org.openscience.cdk:cdk-libiocml:jar:2.8-20220912.161859-40 is missing, no dependency information available
```

I'd very much appreciate any help to get this sorted.

Personally, I consider javadocs as quite important and I struggle to validate them if I add/modify anything.

**Comment by johnmay** [comment]
Ah you need to bootstrap it I think. The old javadoc could pickup run time dependency but that didn’t seem to work anymore (maybe extra module flags needed?) so you need to do the following:- compile your code (main project)- make cdk build utils depend on the new build- rebuild the cdk-build-utils- run javadoc:aggregate on the main projectSince we don’t really add many taglets it’s not normally such a pain although this is one of the reasons I would favour just in-lining the values as plain HTML.- JohnOn 11 Nov 2022, at 07:27, Uli ***@***.***> wrote:﻿
I added some javadoc and tried to generate the javadoc to validate that everything is fine.
However, when executing javadoc:aggregate I run into the following error:
error: An internal exception has occurred. 
  	(java.lang.NoClassDefFoundError: org/xmlcml/cml/element/CMLMolecule)
Please file a bug against the javadoc tool via the Java bug reporting page
(http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com)
for duplicates. Include error messages and the following diagnostic in your report. Thank you.
java.lang.NoClassDefFoundError: org/xmlcml/cml/element/CMLMolecule
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at net.sf.cdk.tools.doclets.CDKIOOptionsTaglet.toString(CDKIOOptionsTaglet.java:89)
	at net.sf.cdk.tools.doclets.CDKIOOptionsTaglet.toString(CDKIOOptionsTaglet.java:130)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.taglets.UserTaglet.getAllBlockTagOutput(UserTaglet.java:125)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.taglets.TagletWriter.getBlockTagOutput(TagletWriter.java:288)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDocletWriter.getBlockTagOutput(HtmlDocletWriter.java:365)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDocletWriter.getBlockTagOutput(HtmlDocletWriter.java:351)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDocletWriter.addTagsInfo(HtmlDocletWriter.java:337)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.ClassWriterImpl.addClassTagInfo(ClassWriterImpl.java:224)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.builders.ClassBuilder.buildClassTagInfo(ClassBuilder.java:316)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.builders.ClassBuilder.buildClassInfo(ClassBuilder.java:185)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.builders.ClassBuilder.buildClassDoc(ClassBuilder.java:147)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.builders.ClassBuilder.build(ClassBuilder.java:113)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDoclet.generateClassFiles(HtmlDoclet.java:388)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.AbstractDoclet.generateClassFiles(AbstractDoclet.java:286)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDoclet.generateClassFiles(HtmlDoclet.java:199)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.AbstractDoclet.startGeneration(AbstractDoclet.java:212)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.AbstractDoclet.run(AbstractDoclet.java:115)
	at jdk.javadoc/jdk.javadoc.doclet.StandardDoclet.run(StandardDoclet.java:103)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:556)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:393)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:342)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
Caused by: java.lang.ClassNotFoundException: org.xmlcml.cml.element.CMLMolecule
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 25 more
5 errors
100 warnings

Command line was: cmd.exe /X /C ""C:\Program Files\Eclipse Adoptium\jdk-17.0.4.101-hotspot\bin\javadoc.exe" @options @packages"

There is a warning earlier on that might be related:
[WARNING] The POM for org.openscience.cdk:cdk-smiles:jar:2.8-20220912.161903-40 is missing, no dependency information available
[WARNING] The POM for org.openscience.cdk:cdk-libiocml:jar:2.8-20220912.161859-40 is missing, no dependency information available

I'd very much appreciate any help to get this sorted.
Personally, I consider javadocs as quite important and I struggle to validate them if I add/modify anything.

**Comment by johnmay** [comment]
Sorry last message got screwed up by email.

Ah you need to bootstrap it I think. 

The old javadoc could pickup run time dependency but that didn’t seem to work anymore (maybe extra module flags needed?) so you need to do the following:
- compile your code (main project)
- make cdk build utils depend on the new build
- rebuild the cdk-build-utils
- run javadoc:aggregate on the main project

Since we don’t really add many taglets it’s not normally such a pain although this is one of the reasons I would favour just in-lining the values as plain HTML.

> Personally, I consider javadocs as quite important and I struggle to validate them if I add/modify anything.

Preaching to the choir, I’m not the one you need to convince. #908

**Comment by egonw** [comment]
@johnmay, we can easily solve hit by putting the JavaDoc taglets in a separate repo than the template and other utilities. I can do this. I think uploading that to Maven Central also makes sense.

Shall I make it so?

**Comment by egonw** [comment]
> Personally, I consider javadocs as quite important and I struggle to validate them if I add/modify anything.

Yes, it is.

**Comment by johnmay** [comment]
I’ve been thinking the correct fix is perhaps the build utils need to be in main project like cdk-test.

Basically at the moment, it’s a complex mess and as @uli notes it raises the bar to javadoc writing.

If the choice is between having some syntactic sugar to “simplify” writing good for the select few vs. making docs easy to build and contribute then I know where I sit

**Comment by uli-f** [comment]
Thank you @johnmay for the instructions that I tried to follow:

1. compile your code (main project)
  1.1 **cdk**: maven `compile` for main project
  1.2 **cdk**: maven `install` so that artifacts get installed into local maven repo

2. make cdk build utils depend on the new build
  2.1 **cdk-build-utils**: change `cdk.version` in `pom.xml` to version installed in local maven repo in step 1

3. rebuild the cdk-build-utils
  3.1 **cdk-build-utils**: maven clean
  3.2 **cdk-build-utils**: maven compile
  3.3 **cdk-build-utils**: maven install
  
4. run javadoc:aggregate on the main project
  4.1 **cdk**: maven javadoc:aggregate

At this point I end up with a different error:

```
Constructing Javadoc information...
1 error
[ERROR] Error while creating javadoc report: 
Exit code: 1 - javadoc: error - In doclet class com.sun.tools.doclets.standard.Standard,  method start has thrown an exception java.lang.reflect.InvocationTargetException
java.lang.NoClassDefFoundError: nu/xom/Node
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at com.sun.tools.doclets.internal.toolkit.taglets.TagletManager.addCustomTag(TagletManager.java:237)
	at com.sun.tools.doclets.internal.toolkit.Configuration.initTagletManager(Configuration.java:595)
	at com.sun.tools.doclets.internal.toolkit.Configuration.setOptions(Configuration.java:544)
	at com.sun.tools.doclets.internal.toolkit.Configuration.setOptions(Configuration.java:554)
	at com.sun.tools.doclets.internal.toolkit.AbstractDoclet.startGeneration(AbstractDoclet.java:134)
	at com.sun.tools.doclets.internal.toolkit.AbstractDoclet.start(AbstractDoclet.java:82)
	at com.sun.tools.doclets.formats.html.HtmlDoclet.start(HtmlDoclet.java:80)
	at com.sun.tools.doclets.standard.Standard.start(Standard.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:310)
	at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:189)
	at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:366)
	at com.sun.tools.javadoc.Start.begin(Start.java:219)
	at com.sun.tools.javadoc.Start.begin(Start.java:205)
	at com.sun.tools.javadoc.Main.execute(Main.java:64)
	at com.sun.tools.javadoc.Main.main(Main.java:54)
Caused by: java.lang.ClassNotFoundException: nu.xom.Node
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 24 more

Command line was: cmd.exe /X /C ""C:\Program Files\Eclipse Adoptium\jdk-8.0.345.1-hotspot\jre\..\bin\javadoc.exe" @options @argfile"
```

tbh: even if this process would have worked it is a major pain.

**Comment by uli-f** [comment]
... and there is another issue with this I'd like to point out.

If I switch the SDK for the project CDK to Java 17, the following error pops up:

```
warning: The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
error: An internal exception has occurred. 
  	(java.lang.NoClassDefFoundError: com/sun/tools/doclets/Taglet)
Please file a bug against the javadoc tool via the Java bug reporting page
(http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com)
for duplicates. Include error messages and the following diagnostic in your report. Thank you.
java.lang.NoClassDefFoundError: com/sun/tools/doclets/Taglet
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.taglets.TagletManager.addCustomTag(TagletManager.java:266)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.BaseConfiguration.initTagletManager(BaseConfiguration.java:450)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.BaseConfiguration.finishOptionSettings0(BaseConfiguration.java:377)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlConfiguration.finishOptionSettings0(HtmlConfiguration.java:421)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.BaseConfiguration.setOptions(BaseConfiguration.java:407)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.AbstractDoclet.startGeneration(AbstractDoclet.java:205)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.AbstractDoclet.run(AbstractDoclet.java:115)
	at jdk.javadoc/jdk.javadoc.doclet.StandardDoclet.run(StandardDoclet.java:103)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:556)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:393)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:342)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.doclets.Taglet
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 23 more
1 error
1 warning

Command line was: cmd.exe /X /C ""C:\Program Files\Eclipse Adoptium\jdk-17.0.4.101-hotspot\bin\javadoc.exe" @options @packages"
```

The namespace for the `Taglet` class has changed. It now lives in `jdk.javadoc.doclet.Taglet`.

**Comment by johnmay** [comment]
Sorry perhaps I misunderstood what you were doing. 

Which build-utils are you using there is one for Jdk 11+ and the old one which no longer works for JDK 8. Currently to build the doc you need to be on JDK 11/17, but we still target 1.8 in the main project.

**Comment by johnmay** [comment]
Can you double check everything on HotSpot 17. There shouldn't be an issue with other versions but just tested locally an everything seems to be OK (other than the HTML warnings).

```
[john@sentinel:cdk-build-util]% java -version
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)
```

```
[john@sentinel:cdk-build-util]% git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

```
[john@sentinel:cdk-build-util]% mvn clean install -q
```

```
[john@sentinel:cdk-build-util]% cd ../cdk
[john@sentinel:cdk]% mvn javadoc:aggregate -q
```

```
8 errors
100 warnings
```

But the doc should be fine:

```

target/site/apidocs/index.html
```

**Comment by uli-f** [comment]
@johnmay Thank you so much for the helpful step-by-step instructions. This worked on the `main` branch of CDK!

I was experimenting with the `rinchi` branch which - admittedly - is a fair bit behind `main` by now. I just switched back to the `rinchi` branch and can re-produce the
`java.lang.NoClassDefFoundError: com/sun/tools/doclets/Taglet`
using Java 17.

I am sorry for wasting your time, my bad. I wanted to get everything in good order before opening a PR for the `rinchi` branch (getting closer now). But it seems like testing javadocs has to wait until after rebasing the `rinchi` branch on main.

**Comment by johnmay** [comment]
No time wasted, you can still it is a little bit flakey and had to make changes recently to get things to work on JDK 11/17. The rebase should (hopefully) we relatively painless.
