### ISSUE TITLE
V3K molfile: Error while parsing index atom X in bond

### ISSUE THREAD

**Issue by rapodaca** [cdk/cdk#943]
Given the following V3K molfile:

```

  Mrv2219 11302223302D          

  0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 2 1 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C -6.458 3.4367 0 0
M  V30 22 C -7.7917 2.6667 0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1 22
M  V30 END BOND
M  V30 END CTAB
M  END
```

I get the following error: "Error while parsing index atom 2 in bond".

AFAICT, the molfile is valid. Replacing atom index 22 in the atom and bond blocks resolves the error.

Here's the stack trace:

```
org.openscience.cdk.io.MDLV3000Reader ERROR: Error while parsing index atom 2 in bond
org.openscience.cdk.exception.CDKException: Error while parsing index atom 2 in bond
        at org.openscience.cdk.io.MDLV3000Reader.readBondBlock(MDLV3000Reader.java:678)
        at org.openscience.cdk.io.MDLV3000Reader.readConnectionTable(MDLV3000Reader.java:193)
        at org.openscience.cdk.io.MDLV3000Reader.readMolecule(MDLV3000Reader.java:166)
        at org.openscience.cdk.io.MDLV3000Reader.read(MDLV3000Reader.java:152)
        at com.companyname.appname.AppTest.testApp(AppTest.java:62)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at junit.framework.TestCase.runTest(TestCase.java:154)
        at junit.framework.TestCase.runBare(TestCase.java:127)
        at junit.framework.TestResult$1.protect(TestResult.java:106)
        at junit.framework.TestResult.runProtected(TestResult.java:124)
        at junit.framework.TestResult.run(TestResult.java:109)
        at junit.framework.TestCase.run(TestCase.java:118)
        at junit.framework.TestSuite.runTest(TestSuite.java:208)
        at junit.framework.TestSuite.run(TestSuite.java:203)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
        at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:121)
        at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:98)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.IndexOutOfBoundsException: No atom at index: 21
        at org.openscience.cdk.silent.AtomContainer2.getAtom(AtomContainer2.java:495)
        at org.openscience.cdk.io.MDLV3000Reader.readBondBlock(MDLV3000Reader.java:672)
        ... 26 more
```

**Comment by johnmay** [comment]
It's been on my list to rewrite the V3000 IO at some point, or rather V2000+V3000 since currently you need to know if you ``.mol`` input is V2000/V3000 before you parse it, which isn't ideal. In general the V3000 reader is not very robust and supports only a subset (bare minimum) of the format, I've added bits over the years but ultimately it needs a rewrite.

In this case the V3000 currently presumes the atom indexes are sequential, indeed all programatically generated content will be sequential. However leave this open since it's a simple fix.

Sure you've tested already but Marvin rejects it:
https://marvinjs-demo.chemaxon.com/latest/

And ChemDraw:
https://chemdrawdirect.perkinelmer.cloud/js/sample/index.html

As expected BIOVIA accepts it:
```
SQL> select smiles(mol('
  Mrv2219 11302223302D          

  0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 2 1 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C -6.458 3.4367 0 0
M  V30 22 C -7.7917 2.6667 0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1 22
M  V30 END BOND
M  V30 END CTAB
M  END')) from dual;
CC
```

You should get a BIOVIA draw license Rich, not expensive for a single user (much cheaper than ChemDraw for example).
