### ISSUE TITLE
OOM in InitialCycles when applying aromaticity

### ISSUE THREAD

**Issue by uli-f** [cdk/cdk#976]
I experience an OOM when applying the aromaticity for this (slightly?) symmetrical structure:

![image](https://github.com/cdk/cdk/assets/98144814/e972470b-fc0d-435c-9488-76aa936023f4)

`C1=CC2=CC3=C1C1=C4C=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC5=C(C=C1)C1=C(C=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C2C=C1)C345`

Here is the stacktrace:
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.openscience.cdk.graph.InitialCycles.indexOfEdge(InitialCycles.java:228)
	at org.openscience.cdk.graph.InitialCycles.toEdgeVector(InitialCycles.java:243)
	at org.openscience.cdk.graph.EssentialCycles$MyCycle.edges(EssentialCycles.java:201)
	at org.openscience.cdk.graph.InitialCycles$Cycle.<init>(InitialCycles.java:500)
	at org.openscience.cdk.graph.EssentialCycles$MyCycle.<init>(EssentialCycles.java:195)
	at org.openscience.cdk.graph.EssentialCycles$MyCycle.<init>(EssentialCycles.java:192)
	at org.openscience.cdk.graph.EssentialCycles.groupByLength(EssentialCycles.java:144)
	at org.openscience.cdk.graph.EssentialCycles.<init>(EssentialCycles.java:104)
	at org.openscience.cdk.graph.Cycles$CycleComputation$2.apply(Cycles.java:881)
	at org.openscience.cdk.graph.Cycles$CycleComputation.find(Cycles.java:1032)
	at org.openscience.cdk.graph.Cycles$Fallback.find(Cycles.java:1234)
	at org.openscience.cdk.aromaticity.Aromaticity.findBonds(Aromaticity.java:200)
	at org.openscience.cdk.aromaticity.Aromaticity.apply(Aromaticity.java:238)
	at org.openscience.cdk.aromaticity.AromaticityTest.outOfMemoryException(AromaticityTest.java:175)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$157/0x0000000801037528.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall$$Lambda$158/0x0000000801037938.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$$Lambda$327/0x00000008010a0cc8.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
```

**Comment by uli-f** [comment]
Opened PR #977 with a test case.

**Comment by johnmay** [comment]
Interesting, the issue with the "phane" structures are there are an exponential amount of essential cycles. If you call the lower level cycles method directly I think you can see how many there are without generating them.

For aromaticity I normally use ``Cycles.or(Cycles.all(), Cycles.all(6))``;

**Comment by johnmay** [comment]
Scrap that, it's relavent cycles I was thinking off and that number is fine:

```java
        IAtomContainer mol = smipar.parseSmiles("C1=CC2=CC3=C1C1=C4C=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC5=C(C=C1)C1=C(C=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C2C=C1)C345");
        Cycles cycles = Cycles.relevant().find(mol);
        System.err.println(cycles.numberOfCycles());
```

Essential: 26
Relevant: 2074

**Comment by johnmay** [comment]
Actually when you remove the C D4 atom (the cross over bit) you end up with: 16,777,240 cycles which is why the you get out of memory. I'm not really sure what the fix is, there really are 16 million essential cycles.

**Comment by uli-f** [comment]
The only thing I can think of is providing some kind of option to put a stop to the cycle finding before the algorithm runs too much in ~cycles~ circles by stopping
- either once a configurable number of cycles is reached
- or a configurable amount of computation time has been spent

My understanding is that even with the best algorithm structures such as the one above might always be very resource-demanding, so the issue as such cannot be fixed but maybe alleviated by allowing to limit the resources spend on this instead of maxing out and being stopped by the JVM resources.

At the moment, I wrapped up the call to Aromaticity::apply in a separate thread and giving it only a certain amount of time to come back to me before getting killed. However, that isn't very reliable as it depends on the machine/environment/etc how much memory can be filled up in that many seconds 🏃🏼 So having the termination criterion based on the number of cycles seems a more reliable and reproducible way to me. Would are your thoughts on this?

**Comment by johnmay** [comment]
Yeah we can check how many there are before and throw and exception if it's too many (5> million is probably reasonable)

**Comment by uli-f** [comment]
> Yeah we can check how many there are before and throw and exception if it's too many (5> million is probably reasonable)

That sounds great! It would be perfect having a reasonable default and the option to go all the way if desired.

Let me know if there is anything I can do to help.

**Comment by johnmay** [comment]
> option to go all the way if desired.

tricky without an an API change
